/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#ifdef _MSC_VER
#pragma optimize("", off)
#elif defined(__clang__)
#pragma clang optimize off
#elif defined(__GNUC__)
#pragma GCC optimize ("O0")
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT = 1,
  aux_sym_line_comment_token1 = 2,
  anon_sym_Hypersignal = 3,
  anon_sym_Jamsignal = 4,
  anon_sym_Alongtimeagoina = 5,
  anon_sym_far_COMMAfaraway_DOT_DOT_DOT = 6,
  anon_sym_Maytheforcebewithyou_DOT = 7,
  anon_sym_Cargo = 8,
  anon_sym_UnloadCargo = 9,
  anon_sym_Holotext = 10,
  anon_sym_Credit = 11,
  anon_sym_Signal = 12,
  anon_sym_Iamabigdealintheresistance_DOT = 13,
  anon_sym_Theforceisstrongwiththisone_DOT = 14,
  anon_sym_That_SQUOTEsonehellofapilot_DOT = 15,
  anon_sym_Iamyourfather_DOT = 16,
  anon_sym_Judgemebymysize_COMMAdoyou_QMARK = 17,
  anon_sym_Executeorder = 18,
  anon_sym_Orderexecuted = 19,
  anon_sym_Starfield = 20,
  sym_identifier = 21,
  anon_sym_DQUOTE = 22,
  anon_sym_DQUOTE2 = 23,
  sym_escape_sequence = 24,
  anon_sym_SQUOTE = 25,
  aux_sym_char_token1 = 26,
  anon_sym_Fromacertainpointofview_DOT = 27,
  anon_sym_That_SQUOTEsimpossible_BANG = 28,
  anon_sym_DASH = 29,
  sym_unsigned_integer = 30,
  sym_string_content = 31,
  sym_source_file = 32,
  sym__definition = 33,
  sym_line_comment = 34,
  sym_extern_function = 35,
  sym_function_definition = 36,
  sym_function_arguments = 37,
  sym_function_argument = 38,
  sym_statement = 39,
  sym_declaration = 40,
  sym_function_call = 41,
  sym_variadic = 42,
  sym_expression = 43,
  sym_literal = 44,
  sym_string = 45,
  sym_char = 46,
  sym_bool = 47,
  sym_integer = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_function_definition_repeat1 = 50,
  aux_sym_function_arguments_repeat1 = 51,
  aux_sym_function_call_repeat1 = 52,
  aux_sym_string_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = "<(-.-)>",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [anon_sym_Hypersignal] = "Hypersignal",
  [anon_sym_Jamsignal] = "Jamsignal",
  [anon_sym_Alongtimeagoina] = "A long time ago in a",
  [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = "far, far away...",
  [anon_sym_Maytheforcebewithyou_DOT] = "May the force be with you.",
  [anon_sym_Cargo] = "Cargo",
  [anon_sym_UnloadCargo] = "UnloadCargo",
  [anon_sym_Holotext] = "Holotext",
  [anon_sym_Credit] = "Credit",
  [anon_sym_Signal] = "Signal",
  [anon_sym_Iamabigdealintheresistance_DOT] = "I am a big deal in the resistance.",
  [anon_sym_Theforceisstrongwiththisone_DOT] = "The force is strong with this one.",
  [anon_sym_That_SQUOTEsonehellofapilot_DOT] = "That's one hell of a pilot.",
  [anon_sym_Iamyourfather_DOT] = "I am your father.",
  [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = "Judge me by my size, do you \?",
  [anon_sym_Executeorder] = "Execute order",
  [anon_sym_Orderexecuted] = "Order executed",
  [anon_sym_Starfield] = "Starfield",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_char_token1] = "char_token1",
  [anon_sym_Fromacertainpointofview_DOT] = "From a certain point of view.",
  [anon_sym_That_SQUOTEsimpossible_BANG] = "That's impossible!",
  [anon_sym_DASH] = "-",
  [sym_unsigned_integer] = "unsigned_integer",
  [sym_string_content] = "string_content",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_line_comment] = "line_comment",
  [sym_extern_function] = "extern_function",
  [sym_function_definition] = "function_definition",
  [sym_function_arguments] = "function_arguments",
  [sym_function_argument] = "function_argument",
  [sym_statement] = "statement",
  [sym_declaration] = "declaration",
  [sym_function_call] = "function_call",
  [sym_variadic] = "variadic",
  [sym_expression] = "expression",
  [sym_literal] = "literal",
  [sym_string] = "string",
  [sym_char] = "char",
  [sym_bool] = "bool",
  [sym_integer] = "integer",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_function_arguments_repeat1] = "function_arguments_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [anon_sym_Hypersignal] = anon_sym_Hypersignal,
  [anon_sym_Jamsignal] = anon_sym_Jamsignal,
  [anon_sym_Alongtimeagoina] = anon_sym_Alongtimeagoina,
  [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = anon_sym_far_COMMAfaraway_DOT_DOT_DOT,
  [anon_sym_Maytheforcebewithyou_DOT] = anon_sym_Maytheforcebewithyou_DOT,
  [anon_sym_Cargo] = anon_sym_Cargo,
  [anon_sym_UnloadCargo] = anon_sym_UnloadCargo,
  [anon_sym_Holotext] = anon_sym_Holotext,
  [anon_sym_Credit] = anon_sym_Credit,
  [anon_sym_Signal] = anon_sym_Signal,
  [anon_sym_Iamabigdealintheresistance_DOT] = anon_sym_Iamabigdealintheresistance_DOT,
  [anon_sym_Theforceisstrongwiththisone_DOT] = anon_sym_Theforceisstrongwiththisone_DOT,
  [anon_sym_That_SQUOTEsonehellofapilot_DOT] = anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [anon_sym_Iamyourfather_DOT] = anon_sym_Iamyourfather_DOT,
  [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = anon_sym_Judgemebymysize_COMMAdoyou_QMARK,
  [anon_sym_Executeorder] = anon_sym_Executeorder,
  [anon_sym_Orderexecuted] = anon_sym_Orderexecuted,
  [anon_sym_Starfield] = anon_sym_Starfield,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_char_token1] = aux_sym_char_token1,
  [anon_sym_Fromacertainpointofview_DOT] = anon_sym_Fromacertainpointofview_DOT,
  [anon_sym_That_SQUOTEsimpossible_BANG] = anon_sym_That_SQUOTEsimpossible_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_unsigned_integer] = sym_unsigned_integer,
  [sym_string_content] = sym_string_content,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_line_comment] = sym_line_comment,
  [sym_extern_function] = sym_extern_function,
  [sym_function_definition] = sym_function_definition,
  [sym_function_arguments] = sym_function_arguments,
  [sym_function_argument] = sym_function_argument,
  [sym_statement] = sym_statement,
  [sym_declaration] = sym_declaration,
  [sym_function_call] = sym_function_call,
  [sym_variadic] = sym_variadic,
  [sym_expression] = sym_expression,
  [sym_literal] = sym_literal,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [sym_bool] = sym_bool,
  [sym_integer] = sym_integer,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_function_arguments_repeat1] = aux_sym_function_arguments_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Hypersignal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Jamsignal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Alongtimeagoina] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Maytheforcebewithyou_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Cargo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UnloadCargo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Holotext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Credit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Signal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Iamabigdealintheresistance_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Theforceisstrongwiththisone_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_That_SQUOTEsonehellofapilot_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Iamyourfather_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Executeorder] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Orderexecuted] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Starfield] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_char_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Fromacertainpointofview_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_That_SQUOTEsimpossible_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_unsigned_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_function_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_variadic] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_count = 1,
  field_id = 2,
  field_name = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_count] = "count",
  [field_id] = "id",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_count, 1},
  [2] =
    {field_id, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 14,
  [38] = 15,
  [39] = 16,
  [40] = 18,
  [41] = 20,
  [42] = 21,
  [43] = 22,
  [44] = 19,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 46,
  [50] = 45,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 70,
  [78] = 78,
  [79] = 73,
  [80] = 71,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(335);
      ADVANCE_MAP(
        '"', 379,
        '\'', 381,
        '-', 396,
        '0', 397,
        '<', 53,
        'C', 383,
        'E', 393,
        'F', 391,
        'H', 390,
        'J', 384,
        'M', 385,
        'O', 392,
        'S', 388,
        'T', 387,
        'U', 389,
        '\\', 302,
        'f', 386,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(333);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(400);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(382);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(178);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(101);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(308);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(72);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(92);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(106);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(149);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(102);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(311);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(253);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(213);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(319);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(284);
      END_STATE();
    case 14:
      if (lookahead == ' ') ADVANCE(152);
      END_STATE();
    case 15:
      if (lookahead == ' ') ADVANCE(88);
      END_STATE();
    case 16:
      if (lookahead == ' ') ADVANCE(274);
      END_STATE();
    case 17:
      if (lookahead == ' ') ADVANCE(187);
      END_STATE();
    case 18:
      if (lookahead == ' ') ADVANCE(100);
      END_STATE();
    case 19:
      if (lookahead == ' ') ADVANCE(212);
      END_STATE();
    case 20:
      if (lookahead == ' ') ADVANCE(150);
      END_STATE();
    case 21:
      if (lookahead == ' ') ADVANCE(121);
      END_STATE();
    case 22:
      if (lookahead == ' ') ADVANCE(114);
      END_STATE();
    case 23:
      if (lookahead == ' ') ADVANCE(78);
      END_STATE();
    case 24:
      if (lookahead == ' ') ADVANCE(239);
      END_STATE();
    case 25:
      if (lookahead == ' ') ADVANCE(240);
      END_STATE();
    case 26:
      if (lookahead == ' ') ADVANCE(93);
      END_STATE();
    case 27:
      if (lookahead == ' ') ADVANCE(182);
      END_STATE();
    case 28:
      if (lookahead == ' ') ADVANCE(289);
      END_STATE();
    case 29:
      if (lookahead == ' ') ADVANCE(183);
      END_STATE();
    case 30:
      if (lookahead == ' ') ADVANCE(262);
      END_STATE();
    case 31:
      if (lookahead == ' ') ADVANCE(96);
      END_STATE();
    case 32:
      if (lookahead == ' ') ADVANCE(293);
      END_STATE();
    case 33:
      if (lookahead == ' ') ADVANCE(247);
      END_STATE();
    case 34:
      if (lookahead == ' ') ADVANCE(177);
      END_STATE();
    case 35:
      if (lookahead == ' ') ADVANCE(79);
      END_STATE();
    case 36:
      if (lookahead == ' ') ADVANCE(166);
      END_STATE();
    case 37:
      if (lookahead == ' ') ADVANCE(252);
      END_STATE();
    case 38:
      if (lookahead == ' ') ADVANCE(115);
      END_STATE();
    case 39:
      if (lookahead == ' ') ADVANCE(320);
      END_STATE();
    case 40:
      if (lookahead == ' ') ADVANCE(91);
      END_STATE();
    case 41:
      if (lookahead == ' ') ADVANCE(243);
      END_STATE();
    case 42:
      if (lookahead == ' ') ADVANCE(231);
      END_STATE();
    case 43:
      if (lookahead == ' ') ADVANCE(203);
      END_STATE();
    case 44:
      if (lookahead == ' ') ADVANCE(273);
      END_STATE();
    case 45:
      if (lookahead == ' ') ADVANCE(312);
      END_STATE();
    case 46:
      if (lookahead == ' ') ADVANCE(300);
      END_STATE();
    case 47:
      if (lookahead == ' ') ADVANCE(154);
      END_STATE();
    case 48:
      if (lookahead == '!') ADVANCE(395);
      END_STATE();
    case 49:
      ADVANCE_MAP(
        '"', 378,
        '\'', 381,
        '-', 396,
        '0', 397,
        '<', 53,
        'F', 373,
        'O', 374,
        'T', 370,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(49);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(400);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 50:
      if (lookahead == '"') ADVANCE(378);
      if (lookahead == '\'') ADVANCE(381);
      if (lookahead == '-') ADVANCE(396);
      if (lookahead == '0') ADVANCE(397);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == 'F') ADVANCE(373);
      if (lookahead == 'T') ADVANCE(370);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(50);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(400);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 51:
      if (lookahead == '\'') ADVANCE(272);
      END_STATE();
    case 52:
      if (lookahead == '\'') ADVANCE(281);
      END_STATE();
    case 53:
      if (lookahead == '(') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == ')') ADVANCE(71);
      END_STATE();
    case 55:
      if (lookahead == ',') ADVANCE(22);
      END_STATE();
    case 56:
      if (lookahead == ',') ADVANCE(14);
      END_STATE();
    case 57:
      if (lookahead == '-') ADVANCE(66);
      END_STATE();
    case 58:
      if (lookahead == '-') ADVANCE(54);
      END_STATE();
    case 59:
      if (lookahead == '.') ADVANCE(349);
      END_STATE();
    case 60:
      if (lookahead == '.') ADVANCE(350);
      END_STATE();
    case 61:
      if (lookahead == '.') ADVANCE(358);
      END_STATE();
    case 62:
      if (lookahead == '.') ADVANCE(394);
      END_STATE();
    case 63:
      if (lookahead == '.') ADVANCE(357);
      END_STATE();
    case 64:
      if (lookahead == '.') ADVANCE(359);
      END_STATE();
    case 65:
      if (lookahead == '.') ADVANCE(356);
      END_STATE();
    case 66:
      if (lookahead == '.') ADVANCE(58);
      END_STATE();
    case 67:
      if (lookahead == '.') ADVANCE(59);
      END_STATE();
    case 68:
      if (lookahead == '.') ADVANCE(67);
      END_STATE();
    case 69:
      if (lookahead == '<') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 70:
      if (lookahead == '<') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(382);
      END_STATE();
    case 71:
      if (lookahead == '>') ADVANCE(336);
      END_STATE();
    case 72:
      if (lookahead == '?') ADVANCE(360);
      END_STATE();
    case 73:
      if (lookahead == 'C') ADVANCE(97);
      END_STATE();
    case 74:
      if (lookahead == 'a') ADVANCE(257);
      if (lookahead == 'r') ADVANCE(123);
      END_STATE();
    case 75:
      if (lookahead == 'a') ADVANCE(207);
      if (lookahead == 'u') ADVANCE(113);
      END_STATE();
    case 76:
      if (lookahead == 'a') ADVANCE(316);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(283);
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 78:
      if (lookahead == 'a') ADVANCE(310);
      END_STATE();
    case 79:
      if (lookahead == 'a') ADVANCE(348);
      END_STATE();
    case 80:
      if (lookahead == 'a') ADVANCE(254);
      END_STATE();
    case 81:
      if (lookahead == 'a') ADVANCE(195);
      END_STATE();
    case 82:
      if (lookahead == 'a') ADVANCE(317);
      END_STATE();
    case 83:
      if (lookahead == 'a') ADVANCE(255);
      END_STATE();
    case 84:
      if (lookahead == 'a') ADVANCE(196);
      END_STATE();
    case 85:
      if (lookahead == 'a') ADVANCE(110);
      END_STATE();
    case 86:
      if (lookahead == 'a') ADVANCE(197);
      END_STATE();
    case 87:
      if (lookahead == 'a') ADVANCE(175);
      END_STATE();
    case 88:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 89:
      if (lookahead == 'a') ADVANCE(265);
      END_STATE();
    case 90:
      if (lookahead == 'a') ADVANCE(223);
      END_STATE();
    case 91:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 92:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'y') ADVANCE(238);
      END_STATE();
    case 93:
      if (lookahead == 'a') ADVANCE(211);
      END_STATE();
    case 94:
      if (lookahead == 'a') ADVANCE(299);
      END_STATE();
    case 95:
      if (lookahead == 'a') ADVANCE(205);
      END_STATE();
    case 96:
      if (lookahead == 'a') ADVANCE(161);
      END_STATE();
    case 97:
      if (lookahead == 'a') ADVANCE(263);
      END_STATE();
    case 98:
      if (lookahead == 'a') ADVANCE(301);
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 99:
      if (lookahead == 'b') ADVANCE(202);
      END_STATE();
    case 100:
      if (lookahead == 'b') ADVANCE(189);
      END_STATE();
    case 101:
      if (lookahead == 'b') ADVANCE(318);
      END_STATE();
    case 102:
      if (lookahead == 'b') ADVANCE(141);
      END_STATE();
    case 103:
      if (lookahead == 'c') ADVANCE(307);
      END_STATE();
    case 104:
      if (lookahead == 'c') ADVANCE(133);
      END_STATE();
    case 105:
      if (lookahead == 'c') ADVANCE(304);
      END_STATE();
    case 106:
      if (lookahead == 'c') ADVANCE(132);
      END_STATE();
    case 107:
      if (lookahead == 'c') ADVANCE(136);
      END_STATE();
    case 108:
      if (lookahead == 'c') ADVANCE(139);
      END_STATE();
    case 109:
      if (lookahead == 'd') ADVANCE(179);
      END_STATE();
    case 110:
      if (lookahead == 'd') ADVANCE(73);
      END_STATE();
    case 111:
      if (lookahead == 'd') ADVANCE(363);
      END_STATE();
    case 112:
      if (lookahead == 'd') ADVANCE(362);
      END_STATE();
    case 113:
      if (lookahead == 'd') ADVANCE(156);
      END_STATE();
    case 114:
      if (lookahead == 'd') ADVANCE(248);
      END_STATE();
    case 115:
      if (lookahead == 'd') ADVANCE(140);
      END_STATE();
    case 116:
      if (lookahead == 'd') ADVANCE(127);
      END_STATE();
    case 117:
      if (lookahead == 'd') ADVANCE(135);
      END_STATE();
    case 118:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 119:
      if (lookahead == 'e') ADVANCE(314);
      END_STATE();
    case 120:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 121:
      if (lookahead == 'e') ADVANCE(315);
      END_STATE();
    case 122:
      if (lookahead == 'e') ADVANCE(200);
      END_STATE();
    case 123:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 124:
      if (lookahead == 'e') ADVANCE(309);
      END_STATE();
    case 125:
      if (lookahead == 'e') ADVANCE(269);
      END_STATE();
    case 126:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 127:
      if (lookahead == 'e') ADVANCE(258);
      END_STATE();
    case 128:
      if (lookahead == 'e') ADVANCE(201);
      END_STATE();
    case 129:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 130:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 131:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 132:
      if (lookahead == 'e') ADVANCE(259);
      END_STATE();
    case 133:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 134:
      if (lookahead == 'e') ADVANCE(2);
      END_STATE();
    case 135:
      if (lookahead == 'e') ADVANCE(256);
      END_STATE();
    case 136:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 137:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 138:
      if (lookahead == 'e') ADVANCE(260);
      END_STATE();
    case 139:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 140:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 141:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 142:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 143:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 144:
      if (lookahead == 'e') ADVANCE(276);
      END_STATE();
    case 145:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 146:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 147:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 148:
      if (lookahead == 'f') ADVANCE(181);
      END_STATE();
    case 149:
      if (lookahead == 'f') ADVANCE(241);
      END_STATE();
    case 150:
      if (lookahead == 'f') ADVANCE(94);
      END_STATE();
    case 151:
      if (lookahead == 'f') ADVANCE(3);
      END_STATE();
    case 152:
      if (lookahead == 'f') ADVANCE(89);
      END_STATE();
    case 153:
      if (lookahead == 'f') ADVANCE(40);
      END_STATE();
    case 154:
      if (lookahead == 'f') ADVANCE(249);
      END_STATE();
    case 155:
      if (lookahead == 'g') ADVANCE(214);
      END_STATE();
    case 156:
      if (lookahead == 'g') ADVANCE(126);
      END_STATE();
    case 157:
      if (lookahead == 'g') ADVANCE(228);
      END_STATE();
    case 158:
      if (lookahead == 'g') ADVANCE(229);
      END_STATE();
    case 159:
      if (lookahead == 'g') ADVANCE(38);
      END_STATE();
    case 160:
      if (lookahead == 'g') ADVANCE(217);
      END_STATE();
    case 161:
      if (lookahead == 'g') ADVANCE(246);
      END_STATE();
    case 162:
      if (lookahead == 'g') ADVANCE(32);
      END_STATE();
    case 163:
      if (lookahead == 'g') ADVANCE(218);
      END_STATE();
    case 164:
      if (lookahead == 'g') ADVANCE(45);
      END_STATE();
    case 165:
      if (lookahead == 'h') ADVANCE(147);
      END_STATE();
    case 166:
      if (lookahead == 'h') ADVANCE(128);
      END_STATE();
    case 167:
      if (lookahead == 'h') ADVANCE(12);
      END_STATE();
    case 168:
      if (lookahead == 'h') ADVANCE(28);
      END_STATE();
    case 169:
      if (lookahead == 'h') ADVANCE(138);
      END_STATE();
    case 170:
      if (lookahead == 'h') ADVANCE(142);
      END_STATE();
    case 171:
      if (lookahead == 'h') ADVANCE(191);
      END_STATE();
    case 172:
      if (lookahead == 'h') ADVANCE(98);
      END_STATE();
    case 173:
      if (lookahead == 'i') ADVANCE(155);
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 174:
      if (lookahead == 'i') ADVANCE(322);
      END_STATE();
    case 175:
      if (lookahead == 'i') ADVANCE(221);
      END_STATE();
    case 176:
      if (lookahead == 'i') ADVANCE(99);
      END_STATE();
    case 177:
      if (lookahead == 'i') ADVANCE(208);
      END_STATE();
    case 178:
      if (lookahead == 'i') ADVANCE(208);
      if (lookahead == 'o') ADVANCE(225);
      END_STATE();
    case 179:
      if (lookahead == 'i') ADVANCE(285);
      END_STATE();
    case 180:
      if (lookahead == 'i') ADVANCE(219);
      END_STATE();
    case 181:
      if (lookahead == 'i') ADVANCE(122);
      END_STATE();
    case 182:
      if (lookahead == 'i') ADVANCE(224);
      END_STATE();
    case 183:
      if (lookahead == 'i') ADVANCE(226);
      END_STATE();
    case 184:
      if (lookahead == 'i') ADVANCE(287);
      END_STATE();
    case 185:
      if (lookahead == 'i') ADVANCE(288);
      END_STATE();
    case 186:
      if (lookahead == 'i') ADVANCE(124);
      END_STATE();
    case 187:
      if (lookahead == 'i') ADVANCE(275);
      END_STATE();
    case 188:
      if (lookahead == 'i') ADVANCE(210);
      END_STATE();
    case 189:
      if (lookahead == 'i') ADVANCE(159);
      END_STATE();
    case 190:
      if (lookahead == 'i') ADVANCE(280);
      END_STATE();
    case 191:
      if (lookahead == 'i') ADVANCE(277);
      END_STATE();
    case 192:
      if (lookahead == 'i') ADVANCE(206);
      END_STATE();
    case 193:
      if (lookahead == 'i') ADVANCE(160);
      END_STATE();
    case 194:
      if (lookahead == 'i') ADVANCE(163);
      END_STATE();
    case 195:
      if (lookahead == 'l') ADVANCE(355);
      END_STATE();
    case 196:
      if (lookahead == 'l') ADVANCE(347);
      END_STATE();
    case 197:
      if (lookahead == 'l') ADVANCE(346);
      END_STATE();
    case 198:
      if (lookahead == 'l') ADVANCE(232);
      END_STATE();
    case 199:
      if (lookahead == 'l') ADVANCE(234);
      END_STATE();
    case 200:
      if (lookahead == 'l') ADVANCE(111);
      END_STATE();
    case 201:
      if (lookahead == 'l') ADVANCE(204);
      END_STATE();
    case 202:
      if (lookahead == 'l') ADVANCE(120);
      END_STATE();
    case 203:
      if (lookahead == 'l') ADVANCE(242);
      END_STATE();
    case 204:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 205:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 206:
      if (lookahead == 'l') ADVANCE(245);
      END_STATE();
    case 207:
      if (lookahead == 'm') ADVANCE(270);
      END_STATE();
    case 208:
      if (lookahead == 'm') ADVANCE(251);
      END_STATE();
    case 209:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 210:
      if (lookahead == 'm') ADVANCE(145);
      END_STATE();
    case 211:
      if (lookahead == 'm') ADVANCE(5);
      END_STATE();
    case 212:
      if (lookahead == 'm') ADVANCE(321);
      END_STATE();
    case 213:
      if (lookahead == 'm') ADVANCE(134);
      END_STATE();
    case 214:
      if (lookahead == 'n') ADVANCE(81);
      END_STATE();
    case 215:
      if (lookahead == 'n') ADVANCE(164);
      END_STATE();
    case 216:
      if (lookahead == 'n') ADVANCE(162);
      END_STATE();
    case 217:
      if (lookahead == 'n') ADVANCE(84);
      END_STATE();
    case 218:
      if (lookahead == 'n') ADVANCE(86);
      END_STATE();
    case 219:
      if (lookahead == 'n') ADVANCE(296);
      END_STATE();
    case 220:
      if (lookahead == 'n') ADVANCE(130);
      END_STATE();
    case 221:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 222:
      if (lookahead == 'n') ADVANCE(199);
      END_STATE();
    case 223:
      if (lookahead == 'n') ADVANCE(104);
      END_STATE();
    case 224:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 225:
      if (lookahead == 'n') ADVANCE(137);
      END_STATE();
    case 226:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 227:
      if (lookahead == 'o') ADVANCE(198);
      if (lookahead == 'y') ADVANCE(250);
      END_STATE();
    case 228:
      if (lookahead == 'o') ADVANCE(351);
      END_STATE();
    case 229:
      if (lookahead == 'o') ADVANCE(352);
      END_STATE();
    case 230:
      if (lookahead == 'o') ADVANCE(209);
      END_STATE();
    case 231:
      if (lookahead == 'o') ADVANCE(225);
      END_STATE();
    case 232:
      if (lookahead == 'o') ADVANCE(290);
      END_STATE();
    case 233:
      if (lookahead == 'o') ADVANCE(303);
      END_STATE();
    case 234:
      if (lookahead == 'o') ADVANCE(85);
      END_STATE();
    case 235:
      if (lookahead == 'o') ADVANCE(279);
      END_STATE();
    case 236:
      if (lookahead == 'o') ADVANCE(306);
      END_STATE();
    case 237:
      if (lookahead == 'o') ADVANCE(215);
      END_STATE();
    case 238:
      if (lookahead == 'o') ADVANCE(305);
      END_STATE();
    case 239:
      if (lookahead == 'o') ADVANCE(153);
      END_STATE();
    case 240:
      if (lookahead == 'o') ADVANCE(151);
      END_STATE();
    case 241:
      if (lookahead == 'o') ADVANCE(264);
      END_STATE();
    case 242:
      if (lookahead == 'o') ADVANCE(216);
      END_STATE();
    case 243:
      if (lookahead == 'o') ADVANCE(267);
      END_STATE();
    case 244:
      if (lookahead == 'o') ADVANCE(180);
      END_STATE();
    case 245:
      if (lookahead == 'o') ADVANCE(291);
      END_STATE();
    case 246:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 247:
      if (lookahead == 'o') ADVANCE(220);
      END_STATE();
    case 248:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 249:
      if (lookahead == 'o') ADVANCE(268);
      END_STATE();
    case 250:
      if (lookahead == 'p') ADVANCE(125);
      END_STATE();
    case 251:
      if (lookahead == 'p') ADVANCE(235);
      END_STATE();
    case 252:
      if (lookahead == 'p') ADVANCE(244);
      END_STATE();
    case 253:
      if (lookahead == 'p') ADVANCE(192);
      END_STATE();
    case 254:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 255:
      if (lookahead == 'r') ADVANCE(148);
      END_STATE();
    case 256:
      if (lookahead == 'r') ADVANCE(361);
      END_STATE();
    case 257:
      if (lookahead == 'r') ADVANCE(157);
      END_STATE();
    case 258:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 259:
      if (lookahead == 'r') ADVANCE(292);
      END_STATE();
    case 260:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 261:
      if (lookahead == 'r') ADVANCE(237);
      END_STATE();
    case 262:
      if (lookahead == 'r') ADVANCE(144);
      END_STATE();
    case 263:
      if (lookahead == 'r') ADVANCE(158);
      END_STATE();
    case 264:
      if (lookahead == 'r') ADVANCE(107);
      END_STATE();
    case 265:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 266:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 267:
      if (lookahead == 'r') ADVANCE(117);
      END_STATE();
    case 268:
      if (lookahead == 'r') ADVANCE(108);
      END_STATE();
    case 269:
      if (lookahead == 'r') ADVANCE(282);
      END_STATE();
    case 270:
      if (lookahead == 's') ADVANCE(193);
      END_STATE();
    case 271:
      if (lookahead == 's') ADVANCE(176);
      END_STATE();
    case 272:
      if (lookahead == 's') ADVANCE(1);
      END_STATE();
    case 273:
      if (lookahead == 's') ADVANCE(174);
      END_STATE();
    case 274:
      if (lookahead == 's') ADVANCE(294);
      END_STATE();
    case 275:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 276:
      if (lookahead == 's') ADVANCE(190);
      END_STATE();
    case 277:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 278:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 279:
      if (lookahead == 's') ADVANCE(271);
      END_STATE();
    case 280:
      if (lookahead == 's') ADVANCE(295);
      END_STATE();
    case 281:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 282:
      if (lookahead == 's') ADVANCE(194);
      END_STATE();
    case 283:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 284:
      if (lookahead == 't') ADVANCE(165);
      END_STATE();
    case 285:
      if (lookahead == 't') ADVANCE(354);
      END_STATE();
    case 286:
      if (lookahead == 't') ADVANCE(353);
      END_STATE();
    case 287:
      if (lookahead == 't') ADVANCE(167);
      END_STATE();
    case 288:
      if (lookahead == 't') ADVANCE(168);
      END_STATE();
    case 289:
      if (lookahead == 't') ADVANCE(171);
      END_STATE();
    case 290:
      if (lookahead == 't') ADVANCE(119);
      END_STATE();
    case 291:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 292:
      if (lookahead == 't') ADVANCE(87);
      END_STATE();
    case 293:
      if (lookahead == 't') ADVANCE(188);
      END_STATE();
    case 294:
      if (lookahead == 't') ADVANCE(261);
      END_STATE();
    case 295:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 296:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 297:
      if (lookahead == 't') ADVANCE(129);
      END_STATE();
    case 298:
      if (lookahead == 't') ADVANCE(131);
      END_STATE();
    case 299:
      if (lookahead == 't') ADVANCE(169);
      END_STATE();
    case 300:
      if (lookahead == 't') ADVANCE(170);
      END_STATE();
    case 301:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 302:
      if (lookahead == 'u') ADVANCE(323);
      if (lookahead == 'x') ADVANCE(330);
      if (lookahead != 0) ADVANCE(380);
      END_STATE();
    case 303:
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 304:
      if (lookahead == 'u') ADVANCE(297);
      END_STATE();
    case 305:
      if (lookahead == 'u') ADVANCE(266);
      END_STATE();
    case 306:
      if (lookahead == 'u') ADVANCE(4);
      END_STATE();
    case 307:
      if (lookahead == 'u') ADVANCE(298);
      END_STATE();
    case 308:
      if (lookahead == 'v') ADVANCE(186);
      END_STATE();
    case 309:
      if (lookahead == 'w') ADVANCE(62);
      END_STATE();
    case 310:
      if (lookahead == 'w') ADVANCE(82);
      END_STATE();
    case 311:
      if (lookahead == 'w') ADVANCE(184);
      END_STATE();
    case 312:
      if (lookahead == 'w') ADVANCE(185);
      END_STATE();
    case 313:
      if (lookahead == 'x') ADVANCE(118);
      END_STATE();
    case 314:
      if (lookahead == 'x') ADVANCE(286);
      END_STATE();
    case 315:
      if (lookahead == 'x') ADVANCE(146);
      END_STATE();
    case 316:
      if (lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 317:
      if (lookahead == 'y') ADVANCE(68);
      END_STATE();
    case 318:
      if (lookahead == 'y') ADVANCE(19);
      END_STATE();
    case 319:
      if (lookahead == 'y') ADVANCE(233);
      END_STATE();
    case 320:
      if (lookahead == 'y') ADVANCE(236);
      END_STATE();
    case 321:
      if (lookahead == 'y') ADVANCE(44);
      END_STATE();
    case 322:
      if (lookahead == 'z') ADVANCE(143);
      END_STATE();
    case 323:
      if (lookahead == '{') ADVANCE(329);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(327);
      END_STATE();
    case 324:
      if (lookahead == '}') ADVANCE(380);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(324);
      END_STATE();
    case 325:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(398);
      END_STATE();
    case 326:
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(399);
      END_STATE();
    case 327:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(330);
      END_STATE();
    case 328:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(380);
      END_STATE();
    case 329:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(324);
      END_STATE();
    case 330:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(328);
      END_STATE();
    case 331:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(401);
      END_STATE();
    case 332:
      if (eof) ADVANCE(335);
      ADVANCE_MAP(
        '"', 379,
        '<', 53,
        'A', 43,
        'C', 74,
        'E', 313,
        'H', 227,
        'I', 26,
        'J', 75,
        'M', 76,
        'S', 173,
        'T', 172,
        'U', 222,
        '\\', 302,
        'f', 80,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(334);
      END_STATE();
    case 333:
      if (eof) ADVANCE(335);
      ADVANCE_MAP(
        '"', 378,
        '\'', 381,
        '-', 396,
        '0', 397,
        '<', 53,
        'C', 383,
        'E', 393,
        'F', 391,
        'H', 390,
        'J', 384,
        'M', 385,
        'O', 392,
        'S', 388,
        'T', 387,
        'U', 389,
        'f', 386,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(333);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(400);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(382);
      END_STATE();
    case 334:
      if (eof) ADVANCE(335);
      ADVANCE_MAP(
        '<', 53,
        'A', 43,
        'C', 74,
        'E', 313,
        'H', 227,
        'I', 26,
        'J', 75,
        'M', 76,
        'S', 173,
        'T', 172,
        'U', 222,
        'f', 80,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(334);
      END_STATE();
    case 335:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 336:
      ACCEPT_TOKEN(anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT);
      END_STATE();
    case 337:
      ACCEPT_TOKEN(anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 338:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '(') ADVANCE(340);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 339:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == ')') ADVANCE(344);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 340:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '-') ADVANCE(342);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 341:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '-') ADVANCE(339);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 342:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '.') ADVANCE(341);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 343:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '<') ADVANCE(338);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(343);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(345);
      END_STATE();
    case 344:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '>') ADVANCE(337);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 345:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 346:
      ACCEPT_TOKEN(anon_sym_Hypersignal);
      END_STATE();
    case 347:
      ACCEPT_TOKEN(anon_sym_Jamsignal);
      END_STATE();
    case 348:
      ACCEPT_TOKEN(anon_sym_Alongtimeagoina);
      END_STATE();
    case 349:
      ACCEPT_TOKEN(anon_sym_far_COMMAfaraway_DOT_DOT_DOT);
      END_STATE();
    case 350:
      ACCEPT_TOKEN(anon_sym_Maytheforcebewithyou_DOT);
      END_STATE();
    case 351:
      ACCEPT_TOKEN(anon_sym_Cargo);
      END_STATE();
    case 352:
      ACCEPT_TOKEN(anon_sym_UnloadCargo);
      END_STATE();
    case 353:
      ACCEPT_TOKEN(anon_sym_Holotext);
      END_STATE();
    case 354:
      ACCEPT_TOKEN(anon_sym_Credit);
      END_STATE();
    case 355:
      ACCEPT_TOKEN(anon_sym_Signal);
      END_STATE();
    case 356:
      ACCEPT_TOKEN(anon_sym_Iamabigdealintheresistance_DOT);
      END_STATE();
    case 357:
      ACCEPT_TOKEN(anon_sym_Theforceisstrongwiththisone_DOT);
      END_STATE();
    case 358:
      ACCEPT_TOKEN(anon_sym_That_SQUOTEsonehellofapilot_DOT);
      END_STATE();
    case 359:
      ACCEPT_TOKEN(anon_sym_Iamyourfather_DOT);
      END_STATE();
    case 360:
      ACCEPT_TOKEN(anon_sym_Judgemebymysize_COMMAdoyou_QMARK);
      END_STATE();
    case 361:
      ACCEPT_TOKEN(anon_sym_Executeorder);
      END_STATE();
    case 362:
      ACCEPT_TOKEN(anon_sym_Orderexecuted);
      END_STATE();
    case 363:
      ACCEPT_TOKEN(anon_sym_Starfield);
      END_STATE();
    case 364:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 365:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 366:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'') ADVANCE(278);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 367:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(376);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 368:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(369);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 369:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(375);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 370:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(367);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 371:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(364);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 372:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(371);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 373:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(372);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 374:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(368);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 375:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(365);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 376:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(366);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 377:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(377);
      END_STATE();
    case 378:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 379:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 380:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 381:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 382:
      ACCEPT_TOKEN(aux_sym_char_token1);
      END_STATE();
    case 383:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(257);
      if (lookahead == 'r') ADVANCE(123);
      END_STATE();
    case 384:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(207);
      if (lookahead == 'u') ADVANCE(113);
      END_STATE();
    case 385:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(316);
      END_STATE();
    case 386:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(254);
      END_STATE();
    case 387:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'h') ADVANCE(77);
      END_STATE();
    case 388:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'i') ADVANCE(155);
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 389:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'n') ADVANCE(199);
      END_STATE();
    case 390:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'o') ADVANCE(198);
      if (lookahead == 'y') ADVANCE(250);
      END_STATE();
    case 391:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'r') ADVANCE(230);
      END_STATE();
    case 392:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'r') ADVANCE(116);
      END_STATE();
    case 393:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'x') ADVANCE(118);
      END_STATE();
    case 394:
      ACCEPT_TOKEN(anon_sym_Fromacertainpointofview_DOT);
      END_STATE();
    case 395:
      ACCEPT_TOKEN(anon_sym_That_SQUOTEsimpossible_BANG);
      END_STATE();
    case 396:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 397:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (lookahead == 'b') ADVANCE(325);
      if (lookahead == 'o') ADVANCE(326);
      if (lookahead == 'x') ADVANCE(331);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(400);
      END_STATE();
    case 398:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(398);
      END_STATE();
    case 399:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(399);
      END_STATE();
    case 400:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(400);
      END_STATE();
    case 401:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(401);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 332},
  [2] = {.lex_state = 49},
  [3] = {.lex_state = 49},
  [4] = {.lex_state = 49},
  [5] = {.lex_state = 50},
  [6] = {.lex_state = 332},
  [7] = {.lex_state = 332},
  [8] = {.lex_state = 332},
  [9] = {.lex_state = 332},
  [10] = {.lex_state = 332},
  [11] = {.lex_state = 332},
  [12] = {.lex_state = 332},
  [13] = {.lex_state = 332},
  [14] = {.lex_state = 49},
  [15] = {.lex_state = 49},
  [16] = {.lex_state = 49},
  [17] = {.lex_state = 49},
  [18] = {.lex_state = 49},
  [19] = {.lex_state = 49},
  [20] = {.lex_state = 49},
  [21] = {.lex_state = 49},
  [22] = {.lex_state = 49},
  [23] = {.lex_state = 332},
  [24] = {.lex_state = 332},
  [25] = {.lex_state = 332},
  [26] = {.lex_state = 332},
  [27] = {.lex_state = 332},
  [28] = {.lex_state = 332},
  [29] = {.lex_state = 332},
  [30] = {.lex_state = 332},
  [31] = {.lex_state = 332},
  [32] = {.lex_state = 332},
  [33] = {.lex_state = 332},
  [34] = {.lex_state = 332},
  [35] = {.lex_state = 332},
  [36] = {.lex_state = 332},
  [37] = {.lex_state = 332},
  [38] = {.lex_state = 332},
  [39] = {.lex_state = 332},
  [40] = {.lex_state = 332},
  [41] = {.lex_state = 332},
  [42] = {.lex_state = 332},
  [43] = {.lex_state = 332},
  [44] = {.lex_state = 332},
  [45] = {.lex_state = 332, .external_lex_state = 1},
  [46] = {.lex_state = 332, .external_lex_state = 1},
  [47] = {.lex_state = 332, .external_lex_state = 1},
  [48] = {.lex_state = 332},
  [49] = {.lex_state = 332, .external_lex_state = 1},
  [50] = {.lex_state = 332, .external_lex_state = 1},
  [51] = {.lex_state = 332},
  [52] = {.lex_state = 332},
  [53] = {.lex_state = 332},
  [54] = {.lex_state = 332, .external_lex_state = 1},
  [55] = {.lex_state = 332},
  [56] = {.lex_state = 332},
  [57] = {.lex_state = 332},
  [58] = {.lex_state = 332},
  [59] = {.lex_state = 332},
  [60] = {.lex_state = 332},
  [61] = {.lex_state = 332},
  [62] = {.lex_state = 332},
  [63] = {.lex_state = 332},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 69},
  [66] = {.lex_state = 332},
  [67] = {.lex_state = 332},
  [68] = {.lex_state = 332},
  [69] = {.lex_state = 69},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 70},
  [72] = {.lex_state = 69},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 69},
  [75] = {.lex_state = 69},
  [76] = {.lex_state = 343},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 70},
  [81] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = ACTIONS(3),
    [anon_sym_Hypersignal] = ACTIONS(1),
    [anon_sym_Jamsignal] = ACTIONS(1),
    [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_Maytheforcebewithyou_DOT] = ACTIONS(1),
    [anon_sym_Cargo] = ACTIONS(1),
    [anon_sym_UnloadCargo] = ACTIONS(1),
    [anon_sym_Holotext] = ACTIONS(1),
    [anon_sym_Credit] = ACTIONS(1),
    [anon_sym_Signal] = ACTIONS(1),
    [anon_sym_Theforceisstrongwiththisone_DOT] = ACTIONS(1),
    [anon_sym_That_SQUOTEsonehellofapilot_DOT] = ACTIONS(1),
    [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = ACTIONS(1),
    [anon_sym_Executeorder] = ACTIONS(1),
    [anon_sym_Orderexecuted] = ACTIONS(1),
    [anon_sym_Starfield] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_char_token1] = ACTIONS(1),
    [anon_sym_Fromacertainpointofview_DOT] = ACTIONS(1),
    [anon_sym_That_SQUOTEsimpossible_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_unsigned_integer] = ACTIONS(1),
    [sym_string_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(64),
    [sym__definition] = STATE(62),
    [sym_line_comment] = STATE(1),
    [sym_extern_function] = STATE(61),
    [sym_function_definition] = STATE(61),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = ACTIONS(3),
    [anon_sym_Hypersignal] = ACTIONS(7),
    [anon_sym_Alongtimeagoina] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(11), 1,
      anon_sym_Orderexecuted,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(16), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      anon_sym_DASH,
    ACTIONS(28), 1,
      sym_unsigned_integer,
    STATE(14), 1,
      sym_literal,
    STATE(17), 1,
      sym_expression,
    ACTIONS(22), 2,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
    STATE(2), 2,
      sym_line_comment,
      aux_sym_function_call_repeat1,
    STATE(18), 4,
      sym_string,
      sym_char,
      sym_bool,
      sym_integer,
  [42] = 13,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(31), 1,
      anon_sym_Orderexecuted,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      sym_unsigned_integer,
    STATE(3), 1,
      sym_line_comment,
    STATE(4), 1,
      aux_sym_function_call_repeat1,
    STATE(14), 1,
      sym_literal,
    STATE(17), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
    STATE(18), 4,
      sym_string,
      sym_char,
      sym_bool,
      sym_integer,
  [86] = 13,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      sym_unsigned_integer,
    ACTIONS(45), 1,
      anon_sym_Orderexecuted,
    STATE(2), 1,
      aux_sym_function_call_repeat1,
    STATE(4), 1,
      sym_line_comment,
    STATE(14), 1,
      sym_literal,
    STATE(17), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
    STATE(18), 4,
      sym_string,
      sym_char,
      sym_bool,
      sym_integer,
  [130] = 11,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    ACTIONS(51), 1,
      anon_sym_SQUOTE,
    ACTIONS(55), 1,
      anon_sym_DASH,
    ACTIONS(57), 1,
      sym_unsigned_integer,
    STATE(5), 1,
      sym_line_comment,
    STATE(33), 1,
      sym_expression,
    STATE(37), 1,
      sym_literal,
    ACTIONS(53), 2,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
    STATE(40), 4,
      sym_string,
      sym_char,
      sym_bool,
      sym_integer,
  [168] = 12,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(59), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    ACTIONS(61), 1,
      anon_sym_Cargo,
    ACTIONS(65), 1,
      anon_sym_Executeorder,
    ACTIONS(67), 1,
      anon_sym_Starfield,
    STATE(6), 1,
      sym_line_comment,
    STATE(7), 1,
      sym_variadic,
    STATE(8), 1,
      sym_function_arguments,
    STATE(9), 1,
      aux_sym_function_definition_repeat1,
    STATE(35), 1,
      sym_statement,
    STATE(32), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(63), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [208] = 10,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(61), 1,
      anon_sym_Cargo,
    ACTIONS(65), 1,
      anon_sym_Executeorder,
    ACTIONS(69), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(7), 1,
      sym_line_comment,
    STATE(10), 1,
      aux_sym_function_definition_repeat1,
    STATE(11), 1,
      sym_function_arguments,
    STATE(35), 1,
      sym_statement,
    STATE(32), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(63), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [242] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(65), 1,
      anon_sym_Executeorder,
    ACTIONS(69), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(8), 1,
      sym_line_comment,
    STATE(10), 1,
      aux_sym_function_definition_repeat1,
    STATE(35), 1,
      sym_statement,
    STATE(32), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(63), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [270] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(65), 1,
      anon_sym_Executeorder,
    ACTIONS(69), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(9), 1,
      sym_line_comment,
    STATE(12), 1,
      aux_sym_function_definition_repeat1,
    STATE(35), 1,
      sym_statement,
    STATE(32), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(63), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [298] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(65), 1,
      anon_sym_Executeorder,
    ACTIONS(71), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(10), 1,
      sym_line_comment,
    STATE(12), 1,
      aux_sym_function_definition_repeat1,
    STATE(35), 1,
      sym_statement,
    STATE(32), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(63), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [326] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(65), 1,
      anon_sym_Executeorder,
    ACTIONS(71), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(11), 1,
      sym_line_comment,
    STATE(13), 1,
      aux_sym_function_definition_repeat1,
    STATE(35), 1,
      sym_statement,
    STATE(32), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(63), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [354] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(73), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    ACTIONS(78), 1,
      anon_sym_Executeorder,
    STATE(35), 1,
      sym_statement,
    STATE(12), 2,
      sym_line_comment,
      aux_sym_function_definition_repeat1,
    STATE(32), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(75), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [380] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(65), 1,
      anon_sym_Executeorder,
    ACTIONS(81), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(12), 1,
      aux_sym_function_definition_repeat1,
    STATE(13), 1,
      sym_line_comment,
    STATE(35), 1,
      sym_statement,
    STATE(32), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(63), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [408] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(85), 1,
      sym_identifier,
    STATE(14), 1,
      sym_line_comment,
    ACTIONS(83), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [427] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(89), 1,
      sym_identifier,
    STATE(15), 1,
      sym_line_comment,
    ACTIONS(87), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [446] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(93), 1,
      sym_identifier,
    STATE(16), 1,
      sym_line_comment,
    ACTIONS(91), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [465] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(97), 1,
      sym_identifier,
    STATE(17), 1,
      sym_line_comment,
    ACTIONS(95), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [484] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(101), 1,
      sym_identifier,
    STATE(18), 1,
      sym_line_comment,
    ACTIONS(99), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [503] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(105), 1,
      sym_identifier,
    STATE(19), 1,
      sym_line_comment,
    ACTIONS(103), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [522] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(20), 1,
      sym_line_comment,
    ACTIONS(107), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [541] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(113), 1,
      sym_identifier,
    STATE(21), 1,
      sym_line_comment,
    ACTIONS(111), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [560] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(22), 1,
      sym_line_comment,
    ACTIONS(115), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [579] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(7), 1,
      anon_sym_Hypersignal,
    ACTIONS(9), 1,
      anon_sym_Alongtimeagoina,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_line_comment,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
    STATE(62), 1,
      sym__definition,
    STATE(61), 2,
      sym_extern_function,
      sym_function_definition,
  [605] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(24), 1,
      sym_line_comment,
    ACTIONS(121), 7,
      anon_sym_Jamsignal,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Cargo,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [621] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 1,
      anon_sym_Hypersignal,
    ACTIONS(128), 1,
      anon_sym_Alongtimeagoina,
    STATE(62), 1,
      sym__definition,
    STATE(25), 2,
      sym_line_comment,
      aux_sym_source_file_repeat1,
    STATE(61), 2,
      sym_extern_function,
      sym_function_definition,
  [645] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(131), 1,
      anon_sym_UnloadCargo,
    STATE(26), 1,
      sym_line_comment,
    STATE(30), 1,
      aux_sym_function_arguments_repeat1,
    STATE(51), 1,
      sym_function_argument,
    ACTIONS(133), 3,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [666] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(27), 1,
      sym_line_comment,
    ACTIONS(135), 6,
      anon_sym_Jamsignal,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [681] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(28), 1,
      sym_line_comment,
    ACTIONS(137), 6,
      anon_sym_Jamsignal,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [696] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(139), 1,
      anon_sym_UnloadCargo,
    STATE(26), 1,
      aux_sym_function_arguments_repeat1,
    STATE(29), 1,
      sym_line_comment,
    STATE(51), 1,
      sym_function_argument,
    ACTIONS(133), 3,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [717] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(141), 1,
      anon_sym_UnloadCargo,
    STATE(51), 1,
      sym_function_argument,
    STATE(30), 2,
      sym_line_comment,
      aux_sym_function_arguments_repeat1,
    ACTIONS(143), 3,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [736] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(61), 1,
      anon_sym_Cargo,
    ACTIONS(67), 1,
      anon_sym_Starfield,
    ACTIONS(146), 1,
      anon_sym_Jamsignal,
    STATE(31), 1,
      sym_line_comment,
    STATE(60), 1,
      sym_variadic,
    STATE(66), 1,
      sym_function_arguments,
  [758] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(32), 1,
      sym_line_comment,
    ACTIONS(148), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [772] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(33), 1,
      sym_line_comment,
    ACTIONS(150), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [786] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(34), 1,
      sym_line_comment,
    ACTIONS(152), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [800] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(35), 1,
      sym_line_comment,
    ACTIONS(154), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [814] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(36), 1,
      sym_line_comment,
    ACTIONS(156), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [828] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(37), 1,
      sym_line_comment,
    ACTIONS(83), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [842] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(38), 1,
      sym_line_comment,
    ACTIONS(87), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [856] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(39), 1,
      sym_line_comment,
    ACTIONS(91), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [870] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(40), 1,
      sym_line_comment,
    ACTIONS(99), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [884] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(41), 1,
      sym_line_comment,
    ACTIONS(107), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [898] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(42), 1,
      sym_line_comment,
    ACTIONS(111), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [912] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(43), 1,
      sym_line_comment,
    ACTIONS(115), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [926] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(44), 1,
      sym_line_comment,
    ACTIONS(103), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [940] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(158), 1,
      anon_sym_DQUOTE2,
    STATE(45), 1,
      sym_line_comment,
    STATE(46), 1,
      aux_sym_string_repeat1,
    ACTIONS(160), 2,
      sym_string_content,
      sym_escape_sequence,
  [957] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(162), 1,
      anon_sym_DQUOTE2,
    STATE(46), 1,
      sym_line_comment,
    STATE(47), 1,
      aux_sym_string_repeat1,
    ACTIONS(160), 2,
      sym_string_content,
      sym_escape_sequence,
  [974] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(164), 1,
      anon_sym_DQUOTE2,
    ACTIONS(166), 2,
      sym_string_content,
      sym_escape_sequence,
    STATE(47), 2,
      sym_line_comment,
      aux_sym_string_repeat1,
  [989] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(48), 1,
      sym_line_comment,
    ACTIONS(169), 4,
      anon_sym_UnloadCargo,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [1002] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(171), 1,
      anon_sym_DQUOTE2,
    STATE(47), 1,
      aux_sym_string_repeat1,
    STATE(49), 1,
      sym_line_comment,
    ACTIONS(160), 2,
      sym_string_content,
      sym_escape_sequence,
  [1019] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(173), 1,
      anon_sym_DQUOTE2,
    STATE(49), 1,
      aux_sym_string_repeat1,
    STATE(50), 1,
      sym_line_comment,
    ACTIONS(160), 2,
      sym_string_content,
      sym_escape_sequence,
  [1036] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(51), 1,
      sym_line_comment,
    ACTIONS(175), 4,
      anon_sym_UnloadCargo,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [1049] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(52), 1,
      sym_line_comment,
    ACTIONS(177), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [1061] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(53), 1,
      sym_line_comment,
    ACTIONS(179), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [1073] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(54), 1,
      sym_line_comment,
    ACTIONS(181), 3,
      sym_string_content,
      anon_sym_DQUOTE2,
      sym_escape_sequence,
  [1085] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(55), 1,
      sym_line_comment,
    ACTIONS(183), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [1097] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(56), 1,
      sym_line_comment,
    ACTIONS(185), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [1109] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(57), 1,
      sym_line_comment,
    ACTIONS(187), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [1121] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(58), 1,
      sym_line_comment,
    ACTIONS(189), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [1133] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(59), 1,
      sym_line_comment,
    ACTIONS(191), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [1145] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(61), 1,
      anon_sym_Cargo,
    ACTIONS(193), 1,
      anon_sym_Jamsignal,
    STATE(60), 1,
      sym_line_comment,
    STATE(67), 1,
      sym_function_arguments,
  [1161] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(61), 1,
      sym_line_comment,
    ACTIONS(195), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [1173] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(62), 1,
      sym_line_comment,
    ACTIONS(197), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [1185] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(63), 1,
      sym_line_comment,
    ACTIONS(199), 2,
      anon_sym_Iamyourfather_DOT,
      anon_sym_Judgemebymysize_COMMAdoyou_QMARK,
  [1196] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
    STATE(64), 1,
      sym_line_comment,
  [1206] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(203), 1,
      sym_identifier,
    STATE(65), 1,
      sym_line_comment,
  [1216] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(193), 1,
      anon_sym_Jamsignal,
    STATE(66), 1,
      sym_line_comment,
  [1226] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(205), 1,
      anon_sym_Jamsignal,
    STATE(67), 1,
      sym_line_comment,
  [1236] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(207), 1,
      anon_sym_far_COMMAfaraway_DOT_DOT_DOT,
    STATE(68), 1,
      sym_line_comment,
  [1246] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(209), 1,
      sym_identifier,
    STATE(69), 1,
      sym_line_comment,
  [1256] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(211), 1,
      sym_unsigned_integer,
    STATE(70), 1,
      sym_line_comment,
  [1266] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(213), 1,
      aux_sym_char_token1,
    STATE(71), 1,
      sym_line_comment,
  [1276] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(215), 1,
      sym_identifier,
    STATE(72), 1,
      sym_line_comment,
  [1286] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(217), 1,
      anon_sym_SQUOTE,
    STATE(73), 1,
      sym_line_comment,
  [1296] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(219), 1,
      sym_identifier,
    STATE(74), 1,
      sym_line_comment,
  [1306] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(221), 1,
      sym_identifier,
    STATE(75), 1,
      sym_line_comment,
  [1316] = 3,
    ACTIONS(223), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(225), 1,
      aux_sym_line_comment_token1,
    STATE(76), 1,
      sym_line_comment,
  [1326] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(227), 1,
      sym_unsigned_integer,
    STATE(77), 1,
      sym_line_comment,
  [1336] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(229), 1,
      sym_unsigned_integer,
    STATE(78), 1,
      sym_line_comment,
  [1346] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(231), 1,
      anon_sym_SQUOTE,
    STATE(79), 1,
      sym_line_comment,
  [1356] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(233), 1,
      aux_sym_char_token1,
    STATE(80), 1,
      sym_line_comment,
  [1366] = 1,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 130,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 208,
  [SMALL_STATE(8)] = 242,
  [SMALL_STATE(9)] = 270,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 326,
  [SMALL_STATE(12)] = 354,
  [SMALL_STATE(13)] = 380,
  [SMALL_STATE(14)] = 408,
  [SMALL_STATE(15)] = 427,
  [SMALL_STATE(16)] = 446,
  [SMALL_STATE(17)] = 465,
  [SMALL_STATE(18)] = 484,
  [SMALL_STATE(19)] = 503,
  [SMALL_STATE(20)] = 522,
  [SMALL_STATE(21)] = 541,
  [SMALL_STATE(22)] = 560,
  [SMALL_STATE(23)] = 579,
  [SMALL_STATE(24)] = 605,
  [SMALL_STATE(25)] = 621,
  [SMALL_STATE(26)] = 645,
  [SMALL_STATE(27)] = 666,
  [SMALL_STATE(28)] = 681,
  [SMALL_STATE(29)] = 696,
  [SMALL_STATE(30)] = 717,
  [SMALL_STATE(31)] = 736,
  [SMALL_STATE(32)] = 758,
  [SMALL_STATE(33)] = 772,
  [SMALL_STATE(34)] = 786,
  [SMALL_STATE(35)] = 800,
  [SMALL_STATE(36)] = 814,
  [SMALL_STATE(37)] = 828,
  [SMALL_STATE(38)] = 842,
  [SMALL_STATE(39)] = 856,
  [SMALL_STATE(40)] = 870,
  [SMALL_STATE(41)] = 884,
  [SMALL_STATE(42)] = 898,
  [SMALL_STATE(43)] = 912,
  [SMALL_STATE(44)] = 926,
  [SMALL_STATE(45)] = 940,
  [SMALL_STATE(46)] = 957,
  [SMALL_STATE(47)] = 974,
  [SMALL_STATE(48)] = 989,
  [SMALL_STATE(49)] = 1002,
  [SMALL_STATE(50)] = 1019,
  [SMALL_STATE(51)] = 1036,
  [SMALL_STATE(52)] = 1049,
  [SMALL_STATE(53)] = 1061,
  [SMALL_STATE(54)] = 1073,
  [SMALL_STATE(55)] = 1085,
  [SMALL_STATE(56)] = 1097,
  [SMALL_STATE(57)] = 1109,
  [SMALL_STATE(58)] = 1121,
  [SMALL_STATE(59)] = 1133,
  [SMALL_STATE(60)] = 1145,
  [SMALL_STATE(61)] = 1161,
  [SMALL_STATE(62)] = 1173,
  [SMALL_STATE(63)] = 1185,
  [SMALL_STATE(64)] = 1196,
  [SMALL_STATE(65)] = 1206,
  [SMALL_STATE(66)] = 1216,
  [SMALL_STATE(67)] = 1226,
  [SMALL_STATE(68)] = 1236,
  [SMALL_STATE(69)] = 1246,
  [SMALL_STATE(70)] = 1256,
  [SMALL_STATE(71)] = 1266,
  [SMALL_STATE(72)] = 1276,
  [SMALL_STATE(73)] = 1286,
  [SMALL_STATE(74)] = 1296,
  [SMALL_STATE(75)] = 1306,
  [SMALL_STATE(76)] = 1316,
  [SMALL_STATE(77)] = 1326,
  [SMALL_STATE(78)] = 1336,
  [SMALL_STATE(79)] = 1346,
  [SMALL_STATE(80)] = 1356,
  [SMALL_STATE(81)] = 1366,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variadic, 2, 0, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_arguments, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_arguments, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_arguments_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_argument, 2, 0, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_arguments_repeat1, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_function, 4, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, 0, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_function, 3, 0, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_function, 5, 0, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [201] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_string_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_string_content] = sym_string_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_string_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_hsl_external_scanner_create(void);
void tree_sitter_hsl_external_scanner_destroy(void *);
bool tree_sitter_hsl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_hsl_external_scanner_serialize(void *, char *);
void tree_sitter_hsl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_hsl_external_scanner_create,
      tree_sitter_hsl_external_scanner_destroy,
      tree_sitter_hsl_external_scanner_scan,
      tree_sitter_hsl_external_scanner_serialize,
      tree_sitter_hsl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "hsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
