/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#ifdef _MSC_VER
#pragma optimize("", off)
#elif defined(__clang__)
#pragma clang optimize off
#elif defined(__GNUC__)
#pragma GCC optimize ("O0")
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 72
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT = 1,
  aux_sym_line_comment_token1 = 2,
  anon_sym_Hypersignal = 3,
  anon_sym_Jamsignal = 4,
  anon_sym_Alongtimeagoina = 5,
  anon_sym_far_COMMAfaraway_DOT_DOT_DOT = 6,
  anon_sym_Maytheforcebewithyou_DOT = 7,
  anon_sym_Iamabigdealintheresistance_DOT = 8,
  anon_sym_Theforceisstrongwiththisone_DOT = 9,
  anon_sym_That_SQUOTEsonehellofapilot_DOT = 10,
  anon_sym_Iamyourfather_DOT = 11,
  anon_sym_Judgemebymysize_COMMAdoyou_QMARK = 12,
  anon_sym_Executeorder = 13,
  anon_sym_Orderexecuted = 14,
  anon_sym_Starfield = 15,
  sym_identifier = 16,
  anon_sym_DQUOTE = 17,
  anon_sym_DQUOTE2 = 18,
  sym_escape_sequence = 19,
  anon_sym_SQUOTE = 20,
  aux_sym_char_token1 = 21,
  anon_sym_Fromacertainpointofview_DOT = 22,
  anon_sym_That_SQUOTEsimpossible_BANG = 23,
  anon_sym_DASH = 24,
  sym_unsigned_integer = 25,
  sym_string_content = 26,
  sym_source_file = 27,
  sym__definition = 28,
  sym_line_comment = 29,
  sym_extern_definition = 30,
  sym_extern_function = 31,
  sym_function_definition = 32,
  sym_statement = 33,
  sym_declaration = 34,
  sym_function_call = 35,
  sym_variadic = 36,
  sym_expression = 37,
  sym_literal = 38,
  sym_string = 39,
  sym_char = 40,
  sym_bool = 41,
  sym_integer = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_extern_definition_repeat1 = 44,
  aux_sym_function_definition_repeat1 = 45,
  aux_sym_function_call_repeat1 = 46,
  aux_sym_string_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = "<(-.-)>",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [anon_sym_Hypersignal] = "Hypersignal",
  [anon_sym_Jamsignal] = "Jamsignal",
  [anon_sym_Alongtimeagoina] = "A long time ago in a",
  [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = "far, far away...",
  [anon_sym_Maytheforcebewithyou_DOT] = "May the force be with you.",
  [anon_sym_Iamabigdealintheresistance_DOT] = "I am a big deal in the resistance.",
  [anon_sym_Theforceisstrongwiththisone_DOT] = "The force is strong with this one.",
  [anon_sym_That_SQUOTEsonehellofapilot_DOT] = "That's one hell of a pilot.",
  [anon_sym_Iamyourfather_DOT] = "I am your father.",
  [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = "Judge me by my size, do you \?",
  [anon_sym_Executeorder] = "Execute order",
  [anon_sym_Orderexecuted] = "Order executed",
  [anon_sym_Starfield] = "Starfield",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_char_token1] = "char_token1",
  [anon_sym_Fromacertainpointofview_DOT] = "From a certain point of view.",
  [anon_sym_That_SQUOTEsimpossible_BANG] = "That's impossible!",
  [anon_sym_DASH] = "-",
  [sym_unsigned_integer] = "unsigned_integer",
  [sym_string_content] = "string_content",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_line_comment] = "line_comment",
  [sym_extern_definition] = "extern_definition",
  [sym_extern_function] = "extern_function",
  [sym_function_definition] = "function_definition",
  [sym_statement] = "statement",
  [sym_declaration] = "declaration",
  [sym_function_call] = "function_call",
  [sym_variadic] = "variadic",
  [sym_expression] = "expression",
  [sym_literal] = "literal",
  [sym_string] = "string",
  [sym_char] = "char",
  [sym_bool] = "bool",
  [sym_integer] = "integer",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_extern_definition_repeat1] = "extern_definition_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [anon_sym_Hypersignal] = anon_sym_Hypersignal,
  [anon_sym_Jamsignal] = anon_sym_Jamsignal,
  [anon_sym_Alongtimeagoina] = anon_sym_Alongtimeagoina,
  [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = anon_sym_far_COMMAfaraway_DOT_DOT_DOT,
  [anon_sym_Maytheforcebewithyou_DOT] = anon_sym_Maytheforcebewithyou_DOT,
  [anon_sym_Iamabigdealintheresistance_DOT] = anon_sym_Iamabigdealintheresistance_DOT,
  [anon_sym_Theforceisstrongwiththisone_DOT] = anon_sym_Theforceisstrongwiththisone_DOT,
  [anon_sym_That_SQUOTEsonehellofapilot_DOT] = anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [anon_sym_Iamyourfather_DOT] = anon_sym_Iamyourfather_DOT,
  [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = anon_sym_Judgemebymysize_COMMAdoyou_QMARK,
  [anon_sym_Executeorder] = anon_sym_Executeorder,
  [anon_sym_Orderexecuted] = anon_sym_Orderexecuted,
  [anon_sym_Starfield] = anon_sym_Starfield,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_char_token1] = aux_sym_char_token1,
  [anon_sym_Fromacertainpointofview_DOT] = anon_sym_Fromacertainpointofview_DOT,
  [anon_sym_That_SQUOTEsimpossible_BANG] = anon_sym_That_SQUOTEsimpossible_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_unsigned_integer] = sym_unsigned_integer,
  [sym_string_content] = sym_string_content,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_line_comment] = sym_line_comment,
  [sym_extern_definition] = sym_extern_definition,
  [sym_extern_function] = sym_extern_function,
  [sym_function_definition] = sym_function_definition,
  [sym_statement] = sym_statement,
  [sym_declaration] = sym_declaration,
  [sym_function_call] = sym_function_call,
  [sym_variadic] = sym_variadic,
  [sym_expression] = sym_expression,
  [sym_literal] = sym_literal,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [sym_bool] = sym_bool,
  [sym_integer] = sym_integer,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_extern_definition_repeat1] = aux_sym_extern_definition_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Hypersignal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Jamsignal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Alongtimeagoina] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Maytheforcebewithyou_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Iamabigdealintheresistance_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Theforceisstrongwiththisone_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_That_SQUOTEsonehellofapilot_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Iamyourfather_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Executeorder] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Orderexecuted] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Starfield] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_char_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Fromacertainpointofview_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_That_SQUOTEsimpossible_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_unsigned_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_variadic] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extern_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_count = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_count] = "count",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_count, 1},
  [2] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 13,
  [28] = 14,
  [29] = 12,
  [30] = 15,
  [31] = 16,
  [32] = 17,
  [33] = 18,
  [34] = 19,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 37,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 36,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 26,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 66,
  [68] = 62,
  [69] = 57,
  [70] = 63,
  [71] = 71,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(309);
      ADVANCE_MAP(
        '"', 366,
        '\'', 368,
        '-', 381,
        '0', 382,
        '<', 53,
        'E', 377,
        'F', 374,
        'H', 378,
        'J', 370,
        'M', 371,
        'O', 375,
        'S', 376,
        'T', 373,
        '\\', 276,
        'f', 372,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(307);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(385);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(369);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(167);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(96);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(282);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(74);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(89);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(86);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(102);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(260);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(140);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(98);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(285);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(230);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(196);
      END_STATE();
    case 14:
      if (lookahead == ' ') ADVANCE(292);
      END_STATE();
    case 15:
      if (lookahead == ' ') ADVANCE(175);
      END_STATE();
    case 16:
      if (lookahead == ' ') ADVANCE(144);
      END_STATE();
    case 17:
      if (lookahead == ' ') ADVANCE(247);
      END_STATE();
    case 18:
      if (lookahead == ' ') ADVANCE(97);
      END_STATE();
    case 19:
      if (lookahead == ' ') ADVANCE(113);
      END_STATE();
    case 20:
      if (lookahead == ' ') ADVANCE(214);
      END_STATE();
    case 21:
      if (lookahead == ' ') ADVANCE(195);
      END_STATE();
    case 22:
      if (lookahead == ' ') ADVANCE(108);
      END_STATE();
    case 23:
      if (lookahead == ' ') ADVANCE(78);
      END_STATE();
    case 24:
      if (lookahead == ' ') ADVANCE(109);
      END_STATE();
    case 25:
      if (lookahead == ' ') ADVANCE(142);
      END_STATE();
    case 26:
      if (lookahead == ' ') ADVANCE(218);
      END_STATE();
    case 27:
      if (lookahead == ' ') ADVANCE(90);
      END_STATE();
    case 28:
      if (lookahead == ' ') ADVANCE(85);
      END_STATE();
    case 29:
      if (lookahead == ' ') ADVANCE(263);
      END_STATE();
    case 30:
      if (lookahead == ' ') ADVANCE(224);
      END_STATE();
    case 31:
      if (lookahead == ' ') ADVANCE(240);
      END_STATE();
    case 32:
      if (lookahead == ' ') ADVANCE(170);
      END_STATE();
    case 33:
      if (lookahead == ' ') ADVANCE(79);
      END_STATE();
    case 34:
      if (lookahead == ' ') ADVANCE(268);
      END_STATE();
    case 35:
      if (lookahead == ' ') ADVANCE(166);
      END_STATE();
    case 36:
      if (lookahead == ' ') ADVANCE(155);
      END_STATE();
    case 37:
      if (lookahead == ' ') ADVANCE(219);
      END_STATE();
    case 38:
      if (lookahead == ' ') ADVANCE(229);
      END_STATE();
    case 39:
      if (lookahead == ' ') ADVANCE(88);
      END_STATE();
    case 40:
      if (lookahead == ' ') ADVANCE(286);
      END_STATE();
    case 41:
      if (lookahead == ' ') ADVANCE(293);
      END_STATE();
    case 42:
      if (lookahead == ' ') ADVANCE(178);
      END_STATE();
    case 43:
      if (lookahead == ' ') ADVANCE(188);
      END_STATE();
    case 44:
      if (lookahead == ' ') ADVANCE(211);
      END_STATE();
    case 45:
      if (lookahead == ' ') ADVANCE(248);
      END_STATE();
    case 46:
      if (lookahead == ' ') ADVANCE(273);
      END_STATE();
    case 47:
      if (lookahead == ' ') ADVANCE(146);
      END_STATE();
    case 48:
      if (lookahead == '!') ADVANCE(380);
      END_STATE();
    case 49:
      ADVANCE_MAP(
        '"', 365,
        '\'', 368,
        '-', 381,
        '0', 382,
        '<', 53,
        'F', 357,
        'O', 358,
        'T', 348,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(49);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(385);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 50:
      if (lookahead == '"') ADVANCE(365);
      if (lookahead == '\'') ADVANCE(368);
      if (lookahead == '-') ADVANCE(381);
      if (lookahead == '0') ADVANCE(382);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == 'F') ADVANCE(357);
      if (lookahead == 'T') ADVANCE(348);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(50);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(385);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 51:
      if (lookahead == '\'') ADVANCE(249);
      END_STATE();
    case 52:
      if (lookahead == '\'') ADVANCE(256);
      END_STATE();
    case 53:
      if (lookahead == '(') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == ')') ADVANCE(73);
      END_STATE();
    case 55:
      if (lookahead == ',') ADVANCE(22);
      END_STATE();
    case 56:
      if (lookahead == ',') ADVANCE(16);
      END_STATE();
    case 57:
      if (lookahead == '-') ADVANCE(66);
      END_STATE();
    case 58:
      if (lookahead == '-') ADVANCE(54);
      END_STATE();
    case 59:
      if (lookahead == '.') ADVANCE(324);
      END_STATE();
    case 60:
      if (lookahead == '.') ADVANCE(325);
      END_STATE();
    case 61:
      if (lookahead == '.') ADVANCE(328);
      END_STATE();
    case 62:
      if (lookahead == '.') ADVANCE(379);
      END_STATE();
    case 63:
      if (lookahead == '.') ADVANCE(327);
      END_STATE();
    case 64:
      if (lookahead == '.') ADVANCE(329);
      END_STATE();
    case 65:
      if (lookahead == '.') ADVANCE(326);
      END_STATE();
    case 66:
      if (lookahead == '.') ADVANCE(58);
      END_STATE();
    case 67:
      if (lookahead == '.') ADVANCE(59);
      END_STATE();
    case 68:
      if (lookahead == '.') ADVANCE(67);
      END_STATE();
    case 69:
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == 'J') ADVANCE(340);
      if (lookahead == 'S') ADVANCE(363);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 70:
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == 'J') ADVANCE(340);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 71:
      if (lookahead == '<') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 72:
      if (lookahead == '<') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(72);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(369);
      END_STATE();
    case 73:
      if (lookahead == '>') ADVANCE(310);
      END_STATE();
    case 74:
      if (lookahead == '?') ADVANCE(330);
      END_STATE();
    case 75:
      if (lookahead == 'a') ADVANCE(290);
      END_STATE();
    case 76:
      if (lookahead == 'a') ADVANCE(231);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(259);
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 78:
      if (lookahead == 'a') ADVANCE(284);
      END_STATE();
    case 79:
      if (lookahead == 'a') ADVANCE(323);
      END_STATE();
    case 80:
      if (lookahead == 'a') ADVANCE(291);
      END_STATE();
    case 81:
      if (lookahead == 'a') ADVANCE(232);
      END_STATE();
    case 82:
      if (lookahead == 'a') ADVANCE(182);
      END_STATE();
    case 83:
      if (lookahead == 'a') ADVANCE(183);
      END_STATE();
    case 84:
      if (lookahead == 'a') ADVANCE(164);
      END_STATE();
    case 85:
      if (lookahead == 'a') ADVANCE(151);
      END_STATE();
    case 86:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 87:
      if (lookahead == 'a') ADVANCE(201);
      END_STATE();
    case 88:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 89:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'y') ADVANCE(217);
      END_STATE();
    case 90:
      if (lookahead == 'a') ADVANCE(194);
      END_STATE();
    case 91:
      if (lookahead == 'a') ADVANCE(272);
      END_STATE();
    case 92:
      if (lookahead == 'a') ADVANCE(239);
      END_STATE();
    case 93:
      if (lookahead == 'a') ADVANCE(190);
      END_STATE();
    case 94:
      if (lookahead == 'a') ADVANCE(274);
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 95:
      if (lookahead == 'b') ADVANCE(186);
      END_STATE();
    case 96:
      if (lookahead == 'b') ADVANCE(294);
      END_STATE();
    case 97:
      if (lookahead == 'b') ADVANCE(177);
      END_STATE();
    case 98:
      if (lookahead == 'b') ADVANCE(133);
      END_STATE();
    case 99:
      if (lookahead == 'c') ADVANCE(277);
      END_STATE();
    case 100:
      if (lookahead == 'c') ADVANCE(126);
      END_STATE();
    case 101:
      if (lookahead == 'c') ADVANCE(279);
      END_STATE();
    case 102:
      if (lookahead == 'c') ADVANCE(122);
      END_STATE();
    case 103:
      if (lookahead == 'c') ADVANCE(129);
      END_STATE();
    case 104:
      if (lookahead == 'c') ADVANCE(132);
      END_STATE();
    case 105:
      if (lookahead == 'd') ADVANCE(148);
      END_STATE();
    case 106:
      if (lookahead == 'd') ADVANCE(333);
      END_STATE();
    case 107:
      if (lookahead == 'd') ADVANCE(332);
      END_STATE();
    case 108:
      if (lookahead == 'd') ADVANCE(225);
      END_STATE();
    case 109:
      if (lookahead == 'd') ADVANCE(130);
      END_STATE();
    case 110:
      if (lookahead == 'd') ADVANCE(119);
      END_STATE();
    case 111:
      if (lookahead == 'd') ADVANCE(124);
      END_STATE();
    case 112:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 113:
      if (lookahead == 'e') ADVANCE(288);
      END_STATE();
    case 114:
      if (lookahead == 'e') ADVANCE(184);
      END_STATE();
    case 115:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 116:
      if (lookahead == 'e') ADVANCE(244);
      END_STATE();
    case 117:
      if (lookahead == 'e') ADVANCE(283);
      END_STATE();
    case 118:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 119:
      if (lookahead == 'e') ADVANCE(236);
      END_STATE();
    case 120:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 121:
      if (lookahead == 'e') ADVANCE(185);
      END_STATE();
    case 122:
      if (lookahead == 'e') ADVANCE(235);
      END_STATE();
    case 123:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 124:
      if (lookahead == 'e') ADVANCE(233);
      END_STATE();
    case 125:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 126:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 127:
      if (lookahead == 'e') ADVANCE(2);
      END_STATE();
    case 128:
      if (lookahead == 'e') ADVANCE(238);
      END_STATE();
    case 129:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 130:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 131:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 132:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 133:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 134:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 135:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 136:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 137:
      if (lookahead == 'e') ADVANCE(250);
      END_STATE();
    case 138:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 139:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 140:
      if (lookahead == 'f') ADVANCE(216);
      END_STATE();
    case 141:
      if (lookahead == 'f') ADVANCE(169);
      END_STATE();
    case 142:
      if (lookahead == 'f') ADVANCE(91);
      END_STATE();
    case 143:
      if (lookahead == 'f') ADVANCE(3);
      END_STATE();
    case 144:
      if (lookahead == 'f') ADVANCE(92);
      END_STATE();
    case 145:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 146:
      if (lookahead == 'f') ADVANCE(226);
      END_STATE();
    case 147:
      if (lookahead == 'g') ADVANCE(198);
      END_STATE();
    case 148:
      if (lookahead == 'g') ADVANCE(120);
      END_STATE();
    case 149:
      if (lookahead == 'g') ADVANCE(24);
      END_STATE();
    case 150:
      if (lookahead == 'g') ADVANCE(200);
      END_STATE();
    case 151:
      if (lookahead == 'g') ADVANCE(223);
      END_STATE();
    case 152:
      if (lookahead == 'g') ADVANCE(40);
      END_STATE();
    case 153:
      if (lookahead == 'g') ADVANCE(34);
      END_STATE();
    case 154:
      if (lookahead == 'h') ADVANCE(139);
      END_STATE();
    case 155:
      if (lookahead == 'h') ADVANCE(121);
      END_STATE();
    case 156:
      if (lookahead == 'h') ADVANCE(14);
      END_STATE();
    case 157:
      if (lookahead == 'h') ADVANCE(29);
      END_STATE();
    case 158:
      if (lookahead == 'h') ADVANCE(128);
      END_STATE();
    case 159:
      if (lookahead == 'h') ADVANCE(135);
      END_STATE();
    case 160:
      if (lookahead == 'h') ADVANCE(180);
      END_STATE();
    case 161:
      if (lookahead == 'h') ADVANCE(94);
      END_STATE();
    case 162:
      if (lookahead == 'i') ADVANCE(296);
      END_STATE();
    case 163:
      if (lookahead == 'i') ADVANCE(147);
      END_STATE();
    case 164:
      if (lookahead == 'i') ADVANCE(205);
      END_STATE();
    case 165:
      if (lookahead == 'i') ADVANCE(95);
      END_STATE();
    case 166:
      if (lookahead == 'i') ADVANCE(192);
      END_STATE();
    case 167:
      if (lookahead == 'i') ADVANCE(192);
      if (lookahead == 'o') ADVANCE(207);
      END_STATE();
    case 168:
      if (lookahead == 'i') ADVANCE(203);
      END_STATE();
    case 169:
      if (lookahead == 'i') ADVANCE(114);
      END_STATE();
    case 170:
      if (lookahead == 'i') ADVANCE(208);
      END_STATE();
    case 171:
      if (lookahead == 'i') ADVANCE(187);
      END_STATE();
    case 172:
      if (lookahead == 'i') ADVANCE(261);
      END_STATE();
    case 173:
      if (lookahead == 'i') ADVANCE(262);
      END_STATE();
    case 174:
      if (lookahead == 'i') ADVANCE(117);
      END_STATE();
    case 175:
      if (lookahead == 'i') ADVANCE(251);
      END_STATE();
    case 176:
      if (lookahead == 'i') ADVANCE(150);
      END_STATE();
    case 177:
      if (lookahead == 'i') ADVANCE(149);
      END_STATE();
    case 178:
      if (lookahead == 'i') ADVANCE(206);
      END_STATE();
    case 179:
      if (lookahead == 'i') ADVANCE(255);
      END_STATE();
    case 180:
      if (lookahead == 'i') ADVANCE(252);
      END_STATE();
    case 181:
      if (lookahead == 'i') ADVANCE(197);
      END_STATE();
    case 182:
      if (lookahead == 'l') ADVANCE(321);
      END_STATE();
    case 183:
      if (lookahead == 'l') ADVANCE(320);
      END_STATE();
    case 184:
      if (lookahead == 'l') ADVANCE(106);
      END_STATE();
    case 185:
      if (lookahead == 'l') ADVANCE(189);
      END_STATE();
    case 186:
      if (lookahead == 'l') ADVANCE(115);
      END_STATE();
    case 187:
      if (lookahead == 'l') ADVANCE(222);
      END_STATE();
    case 188:
      if (lookahead == 'l') ADVANCE(220);
      END_STATE();
    case 189:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 190:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 191:
      if (lookahead == 'm') ADVANCE(245);
      END_STATE();
    case 192:
      if (lookahead == 'm') ADVANCE(228);
      END_STATE();
    case 193:
      if (lookahead == 'm') ADVANCE(6);
      END_STATE();
    case 194:
      if (lookahead == 'm') ADVANCE(5);
      END_STATE();
    case 195:
      if (lookahead == 'm') ADVANCE(295);
      END_STATE();
    case 196:
      if (lookahead == 'm') ADVANCE(127);
      END_STATE();
    case 197:
      if (lookahead == 'm') ADVANCE(134);
      END_STATE();
    case 198:
      if (lookahead == 'n') ADVANCE(82);
      END_STATE();
    case 199:
      if (lookahead == 'n') ADVANCE(152);
      END_STATE();
    case 200:
      if (lookahead == 'n') ADVANCE(83);
      END_STATE();
    case 201:
      if (lookahead == 'n') ADVANCE(100);
      END_STATE();
    case 202:
      if (lookahead == 'n') ADVANCE(153);
      END_STATE();
    case 203:
      if (lookahead == 'n') ADVANCE(270);
      END_STATE();
    case 204:
      if (lookahead == 'n') ADVANCE(123);
      END_STATE();
    case 205:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 206:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 207:
      if (lookahead == 'n') ADVANCE(131);
      END_STATE();
    case 208:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 209:
      if (lookahead == 'o') ADVANCE(193);
      END_STATE();
    case 210:
      if (lookahead == 'o') ADVANCE(278);
      END_STATE();
    case 211:
      if (lookahead == 'o') ADVANCE(207);
      END_STATE();
    case 212:
      if (lookahead == 'o') ADVANCE(254);
      END_STATE();
    case 213:
      if (lookahead == 'o') ADVANCE(281);
      END_STATE();
    case 214:
      if (lookahead == 'o') ADVANCE(145);
      END_STATE();
    case 215:
      if (lookahead == 'o') ADVANCE(199);
      END_STATE();
    case 216:
      if (lookahead == 'o') ADVANCE(234);
      END_STATE();
    case 217:
      if (lookahead == 'o') ADVANCE(280);
      END_STATE();
    case 218:
      if (lookahead == 'o') ADVANCE(143);
      END_STATE();
    case 219:
      if (lookahead == 'o') ADVANCE(242);
      END_STATE();
    case 220:
      if (lookahead == 'o') ADVANCE(202);
      END_STATE();
    case 221:
      if (lookahead == 'o') ADVANCE(168);
      END_STATE();
    case 222:
      if (lookahead == 'o') ADVANCE(264);
      END_STATE();
    case 223:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 224:
      if (lookahead == 'o') ADVANCE(204);
      END_STATE();
    case 225:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 226:
      if (lookahead == 'o') ADVANCE(243);
      END_STATE();
    case 227:
      if (lookahead == 'p') ADVANCE(116);
      END_STATE();
    case 228:
      if (lookahead == 'p') ADVANCE(212);
      END_STATE();
    case 229:
      if (lookahead == 'p') ADVANCE(221);
      END_STATE();
    case 230:
      if (lookahead == 'p') ADVANCE(171);
      END_STATE();
    case 231:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 232:
      if (lookahead == 'r') ADVANCE(141);
      END_STATE();
    case 233:
      if (lookahead == 'r') ADVANCE(331);
      END_STATE();
    case 234:
      if (lookahead == 'r') ADVANCE(103);
      END_STATE();
    case 235:
      if (lookahead == 'r') ADVANCE(265);
      END_STATE();
    case 236:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 237:
      if (lookahead == 'r') ADVANCE(215);
      END_STATE();
    case 238:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 239:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 240:
      if (lookahead == 'r') ADVANCE(137);
      END_STATE();
    case 241:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 242:
      if (lookahead == 'r') ADVANCE(111);
      END_STATE();
    case 243:
      if (lookahead == 'r') ADVANCE(104);
      END_STATE();
    case 244:
      if (lookahead == 'r') ADVANCE(257);
      END_STATE();
    case 245:
      if (lookahead == 's') ADVANCE(163);
      END_STATE();
    case 246:
      if (lookahead == 's') ADVANCE(165);
      END_STATE();
    case 247:
      if (lookahead == 's') ADVANCE(267);
      END_STATE();
    case 248:
      if (lookahead == 's') ADVANCE(162);
      END_STATE();
    case 249:
      if (lookahead == 's') ADVANCE(1);
      END_STATE();
    case 250:
      if (lookahead == 's') ADVANCE(179);
      END_STATE();
    case 251:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 252:
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 253:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 254:
      if (lookahead == 's') ADVANCE(246);
      END_STATE();
    case 255:
      if (lookahead == 's') ADVANCE(269);
      END_STATE();
    case 256:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 257:
      if (lookahead == 's') ADVANCE(176);
      END_STATE();
    case 258:
      if (lookahead == 't') ADVANCE(81);
      END_STATE();
    case 259:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 260:
      if (lookahead == 't') ADVANCE(154);
      END_STATE();
    case 261:
      if (lookahead == 't') ADVANCE(156);
      END_STATE();
    case 262:
      if (lookahead == 't') ADVANCE(157);
      END_STATE();
    case 263:
      if (lookahead == 't') ADVANCE(160);
      END_STATE();
    case 264:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 265:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 266:
      if (lookahead == 't') ADVANCE(118);
      END_STATE();
    case 267:
      if (lookahead == 't') ADVANCE(237);
      END_STATE();
    case 268:
      if (lookahead == 't') ADVANCE(181);
      END_STATE();
    case 269:
      if (lookahead == 't') ADVANCE(87);
      END_STATE();
    case 270:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 271:
      if (lookahead == 't') ADVANCE(125);
      END_STATE();
    case 272:
      if (lookahead == 't') ADVANCE(158);
      END_STATE();
    case 273:
      if (lookahead == 't') ADVANCE(159);
      END_STATE();
    case 274:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 275:
      if (lookahead == 'u') ADVANCE(105);
      END_STATE();
    case 276:
      if (lookahead == 'u') ADVANCE(297);
      if (lookahead == 'x') ADVANCE(304);
      if (lookahead != 0) ADVANCE(367);
      END_STATE();
    case 277:
      if (lookahead == 'u') ADVANCE(271);
      END_STATE();
    case 278:
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 279:
      if (lookahead == 'u') ADVANCE(266);
      END_STATE();
    case 280:
      if (lookahead == 'u') ADVANCE(241);
      END_STATE();
    case 281:
      if (lookahead == 'u') ADVANCE(4);
      END_STATE();
    case 282:
      if (lookahead == 'v') ADVANCE(174);
      END_STATE();
    case 283:
      if (lookahead == 'w') ADVANCE(62);
      END_STATE();
    case 284:
      if (lookahead == 'w') ADVANCE(80);
      END_STATE();
    case 285:
      if (lookahead == 'w') ADVANCE(172);
      END_STATE();
    case 286:
      if (lookahead == 'w') ADVANCE(173);
      END_STATE();
    case 287:
      if (lookahead == 'x') ADVANCE(112);
      END_STATE();
    case 288:
      if (lookahead == 'x') ADVANCE(138);
      END_STATE();
    case 289:
      if (lookahead == 'y') ADVANCE(227);
      END_STATE();
    case 290:
      if (lookahead == 'y') ADVANCE(8);
      END_STATE();
    case 291:
      if (lookahead == 'y') ADVANCE(68);
      END_STATE();
    case 292:
      if (lookahead == 'y') ADVANCE(210);
      END_STATE();
    case 293:
      if (lookahead == 'y') ADVANCE(213);
      END_STATE();
    case 294:
      if (lookahead == 'y') ADVANCE(21);
      END_STATE();
    case 295:
      if (lookahead == 'y') ADVANCE(45);
      END_STATE();
    case 296:
      if (lookahead == 'z') ADVANCE(136);
      END_STATE();
    case 297:
      if (lookahead == '{') ADVANCE(303);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(301);
      END_STATE();
    case 298:
      if (lookahead == '}') ADVANCE(367);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(298);
      END_STATE();
    case 299:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(383);
      END_STATE();
    case 300:
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(384);
      END_STATE();
    case 301:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(304);
      END_STATE();
    case 302:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(367);
      END_STATE();
    case 303:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(298);
      END_STATE();
    case 304:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(302);
      END_STATE();
    case 305:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(386);
      END_STATE();
    case 306:
      if (eof) ADVANCE(309);
      ADVANCE_MAP(
        '"', 366,
        '<', 53,
        'A', 43,
        'E', 287,
        'H', 289,
        'I', 27,
        'J', 275,
        'M', 75,
        'S', 258,
        'T', 161,
        '\\', 276,
        'f', 76,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(308);
      END_STATE();
    case 307:
      if (eof) ADVANCE(309);
      ADVANCE_MAP(
        '"', 365,
        '\'', 368,
        '-', 381,
        '0', 382,
        '<', 53,
        'E', 377,
        'F', 374,
        'H', 378,
        'J', 370,
        'M', 371,
        'O', 375,
        'S', 376,
        'T', 373,
        'f', 372,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(307);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(385);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(369);
      END_STATE();
    case 308:
      if (eof) ADVANCE(309);
      ADVANCE_MAP(
        '<', 53,
        'A', 43,
        'E', 287,
        'H', 289,
        'I', 27,
        'J', 275,
        'M', 75,
        'S', 258,
        'T', 161,
        'f', 76,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(308);
      END_STATE();
    case 309:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 310:
      ACCEPT_TOKEN(anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT);
      END_STATE();
    case 311:
      ACCEPT_TOKEN(anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(319);
      END_STATE();
    case 312:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '(') ADVANCE(314);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(319);
      END_STATE();
    case 313:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == ')') ADVANCE(318);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(319);
      END_STATE();
    case 314:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '-') ADVANCE(316);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(319);
      END_STATE();
    case 315:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '-') ADVANCE(313);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(319);
      END_STATE();
    case 316:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '.') ADVANCE(315);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(319);
      END_STATE();
    case 317:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '<') ADVANCE(312);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(317);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(319);
      END_STATE();
    case 318:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '>') ADVANCE(311);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(319);
      END_STATE();
    case 319:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(319);
      END_STATE();
    case 320:
      ACCEPT_TOKEN(anon_sym_Hypersignal);
      END_STATE();
    case 321:
      ACCEPT_TOKEN(anon_sym_Jamsignal);
      END_STATE();
    case 322:
      ACCEPT_TOKEN(anon_sym_Jamsignal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 323:
      ACCEPT_TOKEN(anon_sym_Alongtimeagoina);
      END_STATE();
    case 324:
      ACCEPT_TOKEN(anon_sym_far_COMMAfaraway_DOT_DOT_DOT);
      END_STATE();
    case 325:
      ACCEPT_TOKEN(anon_sym_Maytheforcebewithyou_DOT);
      END_STATE();
    case 326:
      ACCEPT_TOKEN(anon_sym_Iamabigdealintheresistance_DOT);
      END_STATE();
    case 327:
      ACCEPT_TOKEN(anon_sym_Theforceisstrongwiththisone_DOT);
      END_STATE();
    case 328:
      ACCEPT_TOKEN(anon_sym_That_SQUOTEsonehellofapilot_DOT);
      END_STATE();
    case 329:
      ACCEPT_TOKEN(anon_sym_Iamyourfather_DOT);
      END_STATE();
    case 330:
      ACCEPT_TOKEN(anon_sym_Judgemebymysize_COMMAdoyou_QMARK);
      END_STATE();
    case 331:
      ACCEPT_TOKEN(anon_sym_Executeorder);
      END_STATE();
    case 332:
      ACCEPT_TOKEN(anon_sym_Orderexecuted);
      END_STATE();
    case 333:
      ACCEPT_TOKEN(anon_sym_Starfield);
      END_STATE();
    case 334:
      ACCEPT_TOKEN(anon_sym_Starfield);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 335:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 336:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 337:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'') ADVANCE(253);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 338:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(362);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 339:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(351);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 340:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(354);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 341:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(359);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 342:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(345);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 343:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(334);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 344:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(352);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 345:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(360);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 346:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(350);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 347:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(355);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 348:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(338);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 349:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(347);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 350:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(344);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 351:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(322);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 352:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(343);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 353:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(335);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 354:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(361);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 355:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(339);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 356:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(353);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 357:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(356);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 358:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(342);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 359:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(346);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 360:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(336);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 361:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(349);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 362:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(337);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 363:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(341);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 364:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(364);
      END_STATE();
    case 365:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 366:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 367:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 368:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 369:
      ACCEPT_TOKEN(aux_sym_char_token1);
      END_STATE();
    case 370:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(191);
      if (lookahead == 'u') ADVANCE(105);
      END_STATE();
    case 371:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(290);
      END_STATE();
    case 372:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(231);
      END_STATE();
    case 373:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'h') ADVANCE(77);
      END_STATE();
    case 374:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'r') ADVANCE(209);
      END_STATE();
    case 375:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'r') ADVANCE(110);
      END_STATE();
    case 376:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 't') ADVANCE(81);
      END_STATE();
    case 377:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'x') ADVANCE(112);
      END_STATE();
    case 378:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'y') ADVANCE(227);
      END_STATE();
    case 379:
      ACCEPT_TOKEN(anon_sym_Fromacertainpointofview_DOT);
      END_STATE();
    case 380:
      ACCEPT_TOKEN(anon_sym_That_SQUOTEsimpossible_BANG);
      END_STATE();
    case 381:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 382:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (lookahead == 'b') ADVANCE(299);
      if (lookahead == 'o') ADVANCE(300);
      if (lookahead == 'x') ADVANCE(305);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(385);
      END_STATE();
    case 383:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(383);
      END_STATE();
    case 384:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(384);
      END_STATE();
    case 385:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(385);
      END_STATE();
    case 386:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(386);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 306},
  [2] = {.lex_state = 49},
  [3] = {.lex_state = 49},
  [4] = {.lex_state = 49},
  [5] = {.lex_state = 50},
  [6] = {.lex_state = 306},
  [7] = {.lex_state = 306},
  [8] = {.lex_state = 306},
  [9] = {.lex_state = 306},
  [10] = {.lex_state = 306},
  [11] = {.lex_state = 49},
  [12] = {.lex_state = 49},
  [13] = {.lex_state = 49},
  [14] = {.lex_state = 49},
  [15] = {.lex_state = 49},
  [16] = {.lex_state = 49},
  [17] = {.lex_state = 49},
  [18] = {.lex_state = 49},
  [19] = {.lex_state = 49},
  [20] = {.lex_state = 306},
  [21] = {.lex_state = 306},
  [22] = {.lex_state = 306},
  [23] = {.lex_state = 306},
  [24] = {.lex_state = 306},
  [25] = {.lex_state = 306},
  [26] = {.lex_state = 306},
  [27] = {.lex_state = 306},
  [28] = {.lex_state = 306},
  [29] = {.lex_state = 306},
  [30] = {.lex_state = 306},
  [31] = {.lex_state = 306},
  [32] = {.lex_state = 306},
  [33] = {.lex_state = 306},
  [34] = {.lex_state = 306},
  [35] = {.lex_state = 306},
  [36] = {.lex_state = 306, .external_lex_state = 1},
  [37] = {.lex_state = 306, .external_lex_state = 1},
  [38] = {.lex_state = 70},
  [39] = {.lex_state = 70},
  [40] = {.lex_state = 306, .external_lex_state = 1},
  [41] = {.lex_state = 306, .external_lex_state = 1},
  [42] = {.lex_state = 69},
  [43] = {.lex_state = 70},
  [44] = {.lex_state = 306, .external_lex_state = 1},
  [45] = {.lex_state = 306},
  [46] = {.lex_state = 306},
  [47] = {.lex_state = 306, .external_lex_state = 1},
  [48] = {.lex_state = 306},
  [49] = {.lex_state = 306},
  [50] = {.lex_state = 306},
  [51] = {.lex_state = 306},
  [52] = {.lex_state = 306},
  [53] = {.lex_state = 70},
  [54] = {.lex_state = 70},
  [55] = {.lex_state = 306},
  [56] = {.lex_state = 70},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 71},
  [59] = {.lex_state = 71},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 71},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 72},
  [64] = {.lex_state = 317},
  [65] = {.lex_state = 306},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 72},
  [71] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = ACTIONS(3),
    [anon_sym_Hypersignal] = ACTIONS(1),
    [anon_sym_Jamsignal] = ACTIONS(1),
    [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_Maytheforcebewithyou_DOT] = ACTIONS(1),
    [anon_sym_Theforceisstrongwiththisone_DOT] = ACTIONS(1),
    [anon_sym_That_SQUOTEsonehellofapilot_DOT] = ACTIONS(1),
    [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = ACTIONS(1),
    [anon_sym_Executeorder] = ACTIONS(1),
    [anon_sym_Orderexecuted] = ACTIONS(1),
    [anon_sym_Starfield] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_char_token1] = ACTIONS(1),
    [anon_sym_Fromacertainpointofview_DOT] = ACTIONS(1),
    [anon_sym_That_SQUOTEsimpossible_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_unsigned_integer] = ACTIONS(1),
    [sym_string_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(60),
    [sym__definition] = STATE(48),
    [sym_line_comment] = STATE(1),
    [sym_extern_definition] = STATE(45),
    [sym_function_definition] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = ACTIONS(3),
    [anon_sym_Hypersignal] = ACTIONS(7),
    [anon_sym_Alongtimeagoina] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(11), 1,
      anon_sym_Orderexecuted,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_unsigned_integer,
    STATE(2), 1,
      sym_line_comment,
    STATE(3), 1,
      aux_sym_function_call_repeat1,
    STATE(11), 1,
      sym_expression,
    STATE(13), 1,
      sym_literal,
    ACTIONS(19), 2,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
    STATE(15), 4,
      sym_string,
      sym_char,
      sym_bool,
      sym_integer,
  [44] = 13,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_unsigned_integer,
    ACTIONS(25), 1,
      anon_sym_Orderexecuted,
    STATE(3), 1,
      sym_line_comment,
    STATE(4), 1,
      aux_sym_function_call_repeat1,
    STATE(11), 1,
      sym_expression,
    STATE(13), 1,
      sym_literal,
    ACTIONS(19), 2,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
    STATE(15), 4,
      sym_string,
      sym_char,
      sym_bool,
      sym_integer,
  [88] = 12,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(27), 1,
      anon_sym_Orderexecuted,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(32), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(44), 1,
      sym_unsigned_integer,
    STATE(11), 1,
      sym_expression,
    STATE(13), 1,
      sym_literal,
    ACTIONS(38), 2,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
    STATE(4), 2,
      sym_line_comment,
      aux_sym_function_call_repeat1,
    STATE(15), 4,
      sym_string,
      sym_char,
      sym_bool,
      sym_integer,
  [130] = 11,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    ACTIONS(51), 1,
      anon_sym_SQUOTE,
    ACTIONS(55), 1,
      anon_sym_DASH,
    ACTIONS(57), 1,
      sym_unsigned_integer,
    STATE(5), 1,
      sym_line_comment,
    STATE(23), 1,
      sym_expression,
    STATE(27), 1,
      sym_literal,
    ACTIONS(53), 2,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
    STATE(30), 4,
      sym_string,
      sym_char,
      sym_bool,
      sym_integer,
  [168] = 10,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(59), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    ACTIONS(63), 1,
      anon_sym_Executeorder,
    ACTIONS(65), 1,
      anon_sym_Starfield,
    STATE(6), 1,
      sym_line_comment,
    STATE(7), 1,
      sym_variadic,
    STATE(10), 1,
      aux_sym_function_definition_repeat1,
    STATE(22), 1,
      sym_statement,
    STATE(25), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(61), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [202] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(63), 1,
      anon_sym_Executeorder,
    ACTIONS(67), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(7), 1,
      sym_line_comment,
    STATE(9), 1,
      aux_sym_function_definition_repeat1,
    STATE(22), 1,
      sym_statement,
    STATE(25), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(61), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [230] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(69), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    ACTIONS(74), 1,
      anon_sym_Executeorder,
    STATE(22), 1,
      sym_statement,
    STATE(8), 2,
      sym_line_comment,
      aux_sym_function_definition_repeat1,
    STATE(25), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(71), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [256] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(63), 1,
      anon_sym_Executeorder,
    ACTIONS(77), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(8), 1,
      aux_sym_function_definition_repeat1,
    STATE(9), 1,
      sym_line_comment,
    STATE(22), 1,
      sym_statement,
    STATE(25), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(61), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [284] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(63), 1,
      anon_sym_Executeorder,
    ACTIONS(67), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(8), 1,
      aux_sym_function_definition_repeat1,
    STATE(10), 1,
      sym_line_comment,
    STATE(22), 1,
      sym_statement,
    STATE(25), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(61), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [312] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(81), 1,
      sym_identifier,
    STATE(11), 1,
      sym_line_comment,
    ACTIONS(79), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [331] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(85), 1,
      sym_identifier,
    STATE(12), 1,
      sym_line_comment,
    ACTIONS(83), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [350] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(89), 1,
      sym_identifier,
    STATE(13), 1,
      sym_line_comment,
    ACTIONS(87), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [369] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(93), 1,
      sym_identifier,
    STATE(14), 1,
      sym_line_comment,
    ACTIONS(91), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [388] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(97), 1,
      sym_identifier,
    STATE(15), 1,
      sym_line_comment,
    ACTIONS(95), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [407] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(101), 1,
      sym_identifier,
    STATE(16), 1,
      sym_line_comment,
    ACTIONS(99), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [426] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(105), 1,
      sym_identifier,
    STATE(17), 1,
      sym_line_comment,
    ACTIONS(103), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [445] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(18), 1,
      sym_line_comment,
    ACTIONS(107), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [464] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(113), 1,
      sym_identifier,
    STATE(19), 1,
      sym_line_comment,
    ACTIONS(111), 7,
      anon_sym_Orderexecuted,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
      anon_sym_DASH,
      sym_unsigned_integer,
  [483] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(7), 1,
      anon_sym_Hypersignal,
    ACTIONS(9), 1,
      anon_sym_Alongtimeagoina,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_line_comment,
    STATE(21), 1,
      aux_sym_source_file_repeat1,
    STATE(48), 1,
      sym__definition,
    STATE(45), 2,
      sym_extern_definition,
      sym_function_definition,
  [509] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    ACTIONS(119), 1,
      anon_sym_Hypersignal,
    ACTIONS(122), 1,
      anon_sym_Alongtimeagoina,
    STATE(48), 1,
      sym__definition,
    STATE(21), 2,
      sym_line_comment,
      aux_sym_source_file_repeat1,
    STATE(45), 2,
      sym_extern_definition,
      sym_function_definition,
  [533] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(22), 1,
      sym_line_comment,
    ACTIONS(125), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [547] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(23), 1,
      sym_line_comment,
    ACTIONS(127), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [561] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(24), 1,
      sym_line_comment,
    ACTIONS(129), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [575] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(25), 1,
      sym_line_comment,
    ACTIONS(131), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [589] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(26), 1,
      sym_line_comment,
    ACTIONS(133), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [603] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(27), 1,
      sym_line_comment,
    ACTIONS(87), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [617] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(28), 1,
      sym_line_comment,
    ACTIONS(91), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [631] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(29), 1,
      sym_line_comment,
    ACTIONS(83), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [645] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(30), 1,
      sym_line_comment,
    ACTIONS(95), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [659] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(31), 1,
      sym_line_comment,
    ACTIONS(99), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [673] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(32), 1,
      sym_line_comment,
    ACTIONS(103), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [687] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(33), 1,
      sym_line_comment,
    ACTIONS(107), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [701] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(34), 1,
      sym_line_comment,
    ACTIONS(111), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [715] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(35), 1,
      sym_line_comment,
    ACTIONS(135), 5,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [729] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(137), 1,
      anon_sym_DQUOTE2,
    STATE(36), 1,
      sym_line_comment,
    STATE(37), 1,
      aux_sym_string_repeat1,
    ACTIONS(139), 2,
      sym_string_content,
      sym_escape_sequence,
  [746] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(141), 1,
      anon_sym_DQUOTE2,
    STATE(37), 1,
      sym_line_comment,
    STATE(41), 1,
      aux_sym_string_repeat1,
    ACTIONS(139), 2,
      sym_string_content,
      sym_escape_sequence,
  [763] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(143), 1,
      anon_sym_Jamsignal,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(38), 1,
      sym_line_comment,
    STATE(43), 1,
      aux_sym_extern_definition_repeat1,
    STATE(56), 1,
      sym_extern_function,
  [782] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(147), 1,
      anon_sym_Jamsignal,
    ACTIONS(149), 1,
      sym_identifier,
    STATE(56), 1,
      sym_extern_function,
    STATE(39), 2,
      sym_line_comment,
      aux_sym_extern_definition_repeat1,
  [799] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(152), 1,
      anon_sym_DQUOTE2,
    STATE(40), 1,
      sym_line_comment,
    STATE(41), 1,
      aux_sym_string_repeat1,
    ACTIONS(139), 2,
      sym_string_content,
      sym_escape_sequence,
  [816] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(154), 1,
      anon_sym_DQUOTE2,
    ACTIONS(156), 2,
      sym_string_content,
      sym_escape_sequence,
    STATE(41), 2,
      sym_line_comment,
      aux_sym_string_repeat1,
  [831] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(161), 1,
      anon_sym_Starfield,
    STATE(42), 1,
      sym_line_comment,
    STATE(54), 1,
      sym_variadic,
    ACTIONS(159), 2,
      anon_sym_Jamsignal,
      sym_identifier,
  [848] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(163), 1,
      anon_sym_Jamsignal,
    STATE(39), 1,
      aux_sym_extern_definition_repeat1,
    STATE(43), 1,
      sym_line_comment,
    STATE(56), 1,
      sym_extern_function,
  [867] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(165), 1,
      anon_sym_DQUOTE2,
    STATE(40), 1,
      aux_sym_string_repeat1,
    STATE(44), 1,
      sym_line_comment,
    ACTIONS(139), 2,
      sym_string_content,
      sym_escape_sequence,
  [884] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(45), 1,
      sym_line_comment,
    ACTIONS(167), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [896] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(46), 1,
      sym_line_comment,
    ACTIONS(169), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [908] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(47), 1,
      sym_line_comment,
    ACTIONS(171), 3,
      sym_string_content,
      anon_sym_DQUOTE2,
      sym_escape_sequence,
  [920] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(48), 1,
      sym_line_comment,
    ACTIONS(173), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [932] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(49), 1,
      sym_line_comment,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [944] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(50), 1,
      sym_line_comment,
    ACTIONS(177), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [956] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(51), 1,
      sym_line_comment,
    ACTIONS(179), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [968] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(52), 1,
      sym_line_comment,
    ACTIONS(181), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [980] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(53), 1,
      sym_line_comment,
    ACTIONS(183), 2,
      anon_sym_Jamsignal,
      sym_identifier,
  [991] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(54), 1,
      sym_line_comment,
    ACTIONS(185), 2,
      anon_sym_Jamsignal,
      sym_identifier,
  [1002] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(55), 1,
      sym_line_comment,
    ACTIONS(187), 2,
      anon_sym_Iamyourfather_DOT,
      anon_sym_Judgemebymysize_COMMAdoyou_QMARK,
  [1013] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(56), 1,
      sym_line_comment,
    ACTIONS(189), 2,
      anon_sym_Jamsignal,
      sym_identifier,
  [1024] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(191), 1,
      sym_unsigned_integer,
    STATE(57), 1,
      sym_line_comment,
  [1034] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(58), 1,
      sym_line_comment,
  [1044] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(59), 1,
      sym_line_comment,
  [1054] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      sym_line_comment,
  [1064] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(199), 1,
      sym_identifier,
    STATE(61), 1,
      sym_line_comment,
  [1074] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(201), 1,
      anon_sym_SQUOTE,
    STATE(62), 1,
      sym_line_comment,
  [1084] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(203), 1,
      aux_sym_char_token1,
    STATE(63), 1,
      sym_line_comment,
  [1094] = 3,
    ACTIONS(205), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(207), 1,
      aux_sym_line_comment_token1,
    STATE(64), 1,
      sym_line_comment,
  [1104] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(209), 1,
      anon_sym_far_COMMAfaraway_DOT_DOT_DOT,
    STATE(65), 1,
      sym_line_comment,
  [1114] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(211), 1,
      sym_unsigned_integer,
    STATE(66), 1,
      sym_line_comment,
  [1124] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(213), 1,
      sym_unsigned_integer,
    STATE(67), 1,
      sym_line_comment,
  [1134] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(215), 1,
      anon_sym_SQUOTE,
    STATE(68), 1,
      sym_line_comment,
  [1144] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(217), 1,
      sym_unsigned_integer,
    STATE(69), 1,
      sym_line_comment,
  [1154] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(219), 1,
      aux_sym_char_token1,
    STATE(70), 1,
      sym_line_comment,
  [1164] = 1,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 130,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 202,
  [SMALL_STATE(8)] = 230,
  [SMALL_STATE(9)] = 256,
  [SMALL_STATE(10)] = 284,
  [SMALL_STATE(11)] = 312,
  [SMALL_STATE(12)] = 331,
  [SMALL_STATE(13)] = 350,
  [SMALL_STATE(14)] = 369,
  [SMALL_STATE(15)] = 388,
  [SMALL_STATE(16)] = 407,
  [SMALL_STATE(17)] = 426,
  [SMALL_STATE(18)] = 445,
  [SMALL_STATE(19)] = 464,
  [SMALL_STATE(20)] = 483,
  [SMALL_STATE(21)] = 509,
  [SMALL_STATE(22)] = 533,
  [SMALL_STATE(23)] = 547,
  [SMALL_STATE(24)] = 561,
  [SMALL_STATE(25)] = 575,
  [SMALL_STATE(26)] = 589,
  [SMALL_STATE(27)] = 603,
  [SMALL_STATE(28)] = 617,
  [SMALL_STATE(29)] = 631,
  [SMALL_STATE(30)] = 645,
  [SMALL_STATE(31)] = 659,
  [SMALL_STATE(32)] = 673,
  [SMALL_STATE(33)] = 687,
  [SMALL_STATE(34)] = 701,
  [SMALL_STATE(35)] = 715,
  [SMALL_STATE(36)] = 729,
  [SMALL_STATE(37)] = 746,
  [SMALL_STATE(38)] = 763,
  [SMALL_STATE(39)] = 782,
  [SMALL_STATE(40)] = 799,
  [SMALL_STATE(41)] = 816,
  [SMALL_STATE(42)] = 831,
  [SMALL_STATE(43)] = 848,
  [SMALL_STATE(44)] = 867,
  [SMALL_STATE(45)] = 884,
  [SMALL_STATE(46)] = 896,
  [SMALL_STATE(47)] = 908,
  [SMALL_STATE(48)] = 920,
  [SMALL_STATE(49)] = 932,
  [SMALL_STATE(50)] = 944,
  [SMALL_STATE(51)] = 956,
  [SMALL_STATE(52)] = 968,
  [SMALL_STATE(53)] = 980,
  [SMALL_STATE(54)] = 991,
  [SMALL_STATE(55)] = 1002,
  [SMALL_STATE(56)] = 1013,
  [SMALL_STATE(57)] = 1024,
  [SMALL_STATE(58)] = 1034,
  [SMALL_STATE(59)] = 1044,
  [SMALL_STATE(60)] = 1054,
  [SMALL_STATE(61)] = 1064,
  [SMALL_STATE(62)] = 1074,
  [SMALL_STATE(63)] = 1084,
  [SMALL_STATE(64)] = 1094,
  [SMALL_STATE(65)] = 1104,
  [SMALL_STATE(66)] = 1114,
  [SMALL_STATE(67)] = 1124,
  [SMALL_STATE(68)] = 1134,
  [SMALL_STATE(69)] = 1144,
  [SMALL_STATE(70)] = 1154,
  [SMALL_STATE(71)] = 1164,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variadic, 2, 0, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_extern_definition_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_extern_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extern_function, 1, 0, 1),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_definition, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_definition, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 3),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variadic, 2, 0, 2),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extern_function, 2, 0, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_extern_definition_repeat1, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [197] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_string_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_string_content] = sym_string_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_string_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_hsl_external_scanner_create(void);
void tree_sitter_hsl_external_scanner_destroy(void *);
bool tree_sitter_hsl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_hsl_external_scanner_serialize(void *, char *);
void tree_sitter_hsl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_hsl_external_scanner_create,
      tree_sitter_hsl_external_scanner_destroy,
      tree_sitter_hsl_external_scanner_scan,
      tree_sitter_hsl_external_scanner_serialize,
      tree_sitter_hsl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "hsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
